/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.usuario.view;
import javax.swing.JOptionPane;
import br.com.ifba.usuario.entity.UsuarioCandidato;
import java.util.regex.Pattern;
import br.com.ifba.usuario.controller.UsuarioCandidatoController;
import br.com.ifba.usuario.service.UsuarioCandidatoService;
import org.springframework.stereotype.Component;

@Component

/**
 * Tela de cadastro do usuário candidato.
 * Coleta os dados pessoais e envia as informações
 * para validação e cadastro via controller.
 * @author luiza
 */

public class CadastroCandidatoView extends javax.swing.JFrame {
    
    private final UsuarioCandidatoController controller =
        new UsuarioCandidatoController(
            new UsuarioCandidatoService()
        );

    /**
     * Creates new form CadastroCandidatoView
     */
    public CadastroCandidatoView() {
        initComponents();
        configurarTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblCadastro = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 50, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));

        lblCadastro.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblCadastro.setForeground(new java.awt.Color(102, 102, 102));
        lblCadastro.setText("Cadastro Usuário");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setText("Nome:");

        lblCpf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCpf.setText("CPF:");

        lblTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTelefone.setText("Telefone:");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEmail.setText("E-mail:");

        lblSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSenha.setText("Senha:");

        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        txtNome.setText("jTextField1");

        txtCpf.setText("jTextField2");

        txtTelefone.setText("jTextField3");

        txtEmail.setText("jTextField4");

        txtSenha.setText("jTextField5");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblSenha)
                        .addGap(18, 18, 18)
                        .addComponent(txtSenha))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblEmail)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmail))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefone))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblCpf)
                        .addGap(31, 31, 31)
                        .addComponent(txtCpf))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addGap(18, 18, 18)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrar)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 590, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void configurarTela() {
    configurarCores();
    configurarFontes();
    configurarCampos();
    configurarBotao();
    setLocationRelativeTo(null);
}
    private void configurarCores() {
    jPanel3.setBackground(new java.awt.Color(0, 51, 51));
    jPanel2.setBackground(new java.awt.Color(239, 238, 238));
    jPanel4.setBackground(java.awt.Color.WHITE);

    lblCadastro.setForeground(new java.awt.Color(80, 80, 80));
    lblNome.setForeground(new java.awt.Color(100, 100, 100));
    lblCpf.setForeground(new java.awt.Color(100, 100, 100));
    lblTelefone.setForeground(new java.awt.Color(100, 100, 100));
    lblEmail.setForeground(new java.awt.Color(100, 100, 100));
    lblSenha.setForeground(new java.awt.Color(100, 100, 100));
}
    private void configurarFontes() {
    lblCadastro.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 30));

    lblNome.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
    lblCpf.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
    lblTelefone.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
    lblEmail.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
    lblSenha.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));

    txtNome.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
    txtCpf.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
    txtTelefone.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
    txtEmail.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
    txtSenha.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
}
    private void configurarCampos() {
    txtNome.setText("");
    txtCpf.setText("");
    txtTelefone.setText("");
    txtEmail.setText("");
    txtSenha.setText("");

    java.awt.Color borda = new java.awt.Color(200, 200, 200);

    txtNome.setBorder(javax.swing.BorderFactory.createLineBorder(borda));
    txtCpf.setBorder(javax.swing.BorderFactory.createLineBorder(borda));
    txtTelefone.setBorder(javax.swing.BorderFactory.createLineBorder(borda));
    txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(borda));
    txtSenha.setBorder(javax.swing.BorderFactory.createLineBorder(borda));
}
    private void configurarBotao() {
    btnCadastrar.setBackground(new java.awt.Color(0, 102, 102));
    btnCadastrar.setForeground(java.awt.Color.WHITE);
    btnCadastrar.setFocusPainted(false);
    btnCadastrar.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
}

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
                                           
    String nome = txtNome.getText();
    String cpf = txtCpf.getText();
    String telefone = txtTelefone.getText();
    String email = txtEmail.getText();
    String senha = txtSenha.getText();

    if (campoVazio(nome) || campoVazio(cpf) || campoVazio(telefone)
            || campoVazio(email) || campoVazio(senha)) {
        JOptionPane.showMessageDialog(this, "Preencha todos os campos.");
        return;
    }

    if (nome.length() < 3) {
        JOptionPane.showMessageDialog(this, "Nome muito curto.");
        return;
    }

    if (!cpfValido(cpf)) {
        JOptionPane.showMessageDialog(this, "CPF inválido (11 números).");
        return;
    }

    if (!telefoneValido(telefone)) {
        JOptionPane.showMessageDialog(this, "Telefone inválido.");
        return;
    }

    if (!emailValido(email)) {
        JOptionPane.showMessageDialog(this, "E-mail inválido.");
        return;
    }

    if (!senhaForte(senha)) {
        JOptionPane.showMessageDialog(this,
            "Senha fraca! Use no mínimo 8 caracteres, letras e números.");
        return;
    }

    UsuarioCandidato candidato = new UsuarioCandidato();
    candidato.setNome(nome);
    candidato.setCpf(cpf);
    candidato.setTelefone(telefone);
    candidato.setEmail(email);
    candidato.setSenha(senha);

    try {
        controller.cadastrar(candidato);

        JOptionPane.showMessageDialog(this,
                "Cadastro realizado com sucesso!");

        new LoginCandidatoView().setVisible(true);
        this.dispose();

    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_btnCadastrarActionPerformed
    private boolean campoVazio(String valor) {
    return valor == null || valor.trim().isEmpty();
}

private boolean emailValido(String email) {
    return Pattern.matches("^[\\w-.]+@([\\w-]+\\.)+[\\w-]{2,4}$", email);
}

private boolean telefoneValido(String telefone) {
    return Pattern.matches("\\d{10,11}", telefone); // só números
}

private boolean cpfValido(String cpf) {
    return Pattern.matches("\\d{11}", cpf);
}

private boolean senhaForte(String senha) {
    return senha.length() >= 8
        && senha.matches(".*[A-Za-z].*")
        && senha.matches(".*\\d.*");
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblCadastro;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
