/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.perfil.empresa.view;

import br.com.ifba.perfil.empresa.controller.PerfilEmpresaIController;
import br.com.ifba.perfil.entity.PerfilEmpresa;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author USER
 */

@Component
@Scope("prototype")
public class TelaEditarSetor extends javax.swing.JFrame {
    
    @Autowired
    private PerfilEmpresaIController perfilEmpresaController;
    private Long idEmpresa;
    private TelaApresentacaoEmpresa telaapresentacao;
    private PerfilEmpresa empresa;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaEditarSetor.class.getName());

    /**
     * Creates new form TelaEditarSetor
     */
    public TelaEditarSetor() {
        initComponents();
    }

     public void setTelaApresentacao(TelaApresentacaoEmpresa tela) {
        this.telaapresentacao = tela;
    }
     
    public void setDados(Long idEmpresa) {
        this.idEmpresa = idEmpresa;
        txtSetor.setText(empresa.getSetor()); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSetor = new javax.swing.JLabel();
        txtSetor = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSetor.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblSetor.setText("SETOR");

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(txtSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(lblSetor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(btnSalvar)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblSetor)
                .addGap(27, 27, 27)
                .addComponent(txtSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnSalvar)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        String novoSetor = txtSetor.getText();
        perfilEmpresaController.addSetor(idEmpresa, novoSetor);
        
        telaapresentacao.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalvarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblSetor;
    private javax.swing.JTextField txtSetor;
    // End of variables declaration//GEN-END:variables
}
