/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.perfil.empresa.view;

import br.com.ifba.infrastructure.spring.SpringContext;
import br.com.ifba.perfil.empresa.controller.PerfilEmpresaIController;
import br.com.ifba.perfil.entity.PerfilEmpresa;
import br.com.ifba.vaga.controller.VagaIController;
import br.com.ifba.vaga.entity.Vaga;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author USER
 */

@Component 
@Scope("protorype")
public class TelaApresentacaoEmpresa extends javax.swing.JFrame {
    
    @Autowired
    private PerfilEmpresaIController perfilEmpresaController;
    private VagaIController vagaController;
    private Long idEmpresa;
    private PerfilEmpresa perfilEmpresa;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaApresentacaoEmpresa.class.getName());

    /**
     * Creates new form TelaApresentacao
     */
    public TelaApresentacaoEmpresa() {
        initComponents();
        atualizarTela();
    }

    private void carregarDadosEmpresa() {
        
        if (perfilEmpresa == null) {
            JOptionPane.showMessageDialog(this, "Empresa não encontrada.");
            return;
        }

        lblnomeempresa.setText(perfilEmpresa.getUsuarioEmpresa().getNome());
        lblDescricao.setText(perfilEmpresa.getSobre());
        lblsetorempresa.setText(perfilEmpresa.getSetor());
    }
    
    /* ===============================
       CARREGAR VAGAS
       =============================== */
    private void carregarVagas() {
        pnlVagas.removeAll();

       List<Vaga> vagas = vagaController.findAll();

        pnlVagas.setLayout(new java.awt.GridLayout(vagas.size(), 1, 5, 5));

        for (Vaga vaga : vagas) {
            JLabel lblVaga = new JLabel("• " + vaga.getTitulo());
            pnlVagas.add(lblVaga);
        }

        pnlVagas.revalidate();
        pnlVagas.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblnomeempresa = new javax.swing.JLabel();
        lblsobre = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        lblsetor = new javax.swing.JLabel();
        lblsetorempresa = new javax.swing.JLabel();
        lblvaga = new javax.swing.JLabel();
        pnlVagas = new javax.swing.JPanel();
        btnInserirSobre = new javax.swing.JButton();
        btnInserirSetor = new javax.swing.JButton();
        pnlEndereco = new javax.swing.JPanel();
        lblpais = new javax.swing.JLabel();
        lblcidade = new javax.swing.JLabel();
        lblestado = new javax.swing.JLabel();
        lblbairro = new javax.swing.JLabel();
        lblnumero = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblinformacoes = new javax.swing.JLabel();
        pnlContato = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblsite = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        btnEditarPerfil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblnomeempresa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblnomeempresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 378, 27));

        lblsobre.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblsobre.setText("SOBRE");
        getContentPane().add(lblsobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        lblDescricao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 384, 100));

        lblsetor.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblsetor.setText("SETOR");
        getContentPane().add(lblsetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, -1, -1));

        lblsetorempresa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblsetorempresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 390, 26));

        lblvaga.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblvaga.setText("VAGAS");
        getContentPane().add(lblvaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, -1, -1));

        pnlVagas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnlVagasLayout = new javax.swing.GroupLayout(pnlVagas);
        pnlVagas.setLayout(pnlVagasLayout);
        pnlVagasLayout.setHorizontalGroup(
            pnlVagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlVagasLayout.setVerticalGroup(
            pnlVagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(pnlVagas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 390, -1));

        btnInserirSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cadastrar.png"))); // NOI18N
        btnInserirSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirSobreActionPerformed(evt);
            }
        });
        getContentPane().add(btnInserirSobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, 20));

        btnInserirSetor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cadastrar.png"))); // NOI18N
        btnInserirSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirSetorActionPerformed(evt);
            }
        });
        getContentPane().add(btnInserirSetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, 20));

        pnlEndereco.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblpais.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblcidade.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblestado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pnlEnderecoLayout = new javax.swing.GroupLayout(pnlEndereco);
        pnlEndereco.setLayout(pnlEnderecoLayout);
        pnlEnderecoLayout.setHorizontalGroup(
            pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnderecoLayout.createSequentialGroup()
                .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblpais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlEnderecoLayout.createSequentialGroup()
                        .addComponent(lblcidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblestado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEnderecoLayout.createSequentialGroup()
                        .addComponent(lblbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblnumero, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlEnderecoLayout.setVerticalGroup(
            pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnderecoLayout.createSequentialGroup()
                .addComponent(lblpais, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblcidade, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                    .addComponent(lblestado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblbairro, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE)
                    .addComponent(lblnumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 370, 70));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblinformacoes.setBackground(new java.awt.Color(204, 0, 0));
        lblinformacoes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblinformacoes.setText("INFORMAÇÕES DE CONTATO");
        jPanel2.add(lblinformacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        pnlContato.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTelefone.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblsite.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pnlContatoLayout = new javax.swing.GroupLayout(pnlContato);
        pnlContato.setLayout(pnlContatoLayout);
        pnlContatoLayout.setHorizontalGroup(
            pnlContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblsite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlContatoLayout.createSequentialGroup()
                        .addComponent(lblTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 138, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlContatoLayout.setVerticalGroup(
            pnlContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContatoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblsite, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(pnlContato, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 148, 370, 90));

        lblEndereco.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEndereco.setText("ENDEREÇO");
        jPanel2.add(lblEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        btnEditarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/editar.png"))); // NOI18N
        btnEditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPerfilActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 30, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirSobreActionPerformed
        // TODO add your handling code here:
        TelaEditarSobre tela = SpringContext.getBean(TelaEditarSobre.class);
            tela.setDados(idEmpresa);
            tela.setTelaApresentacao(this);
            tela.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_btnInserirSobreActionPerformed

    private void btnInserirSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirSetorActionPerformed
        // TODO add your handling code here:
        TelaEditarSetor tela = SpringContext.getBean(TelaEditarSetor.class);
            tela.setDados(idEmpresa);
            tela.setTelaApresentacao(this);
            tela.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_btnInserirSetorActionPerformed

    private void btnEditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPerfilActionPerformed
        // TODO add your handling code here:
        TelaEditarPerfilEmpresa tela =
            SpringContext.getBean(TelaEditarPerfilEmpresa.class);

        tela.setDados(idEmpresa);                 // id da empresa logada
        tela.setTelaApresentacao(this);           // referência para voltar
        tela.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_btnEditarPerfilActionPerformed

    /* ===============================
       MÉTODO PARA ATUALIZAR A TELA
       =============================== */
    public void atualizarTela() {
        carregarDadosEmpresa();
        carregarVagas();
        setVisible(true);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarPerfil;
    private javax.swing.JButton btnInserirSetor;
    private javax.swing.JButton btnInserirSobre;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblbairro;
    private javax.swing.JLabel lblcidade;
    private javax.swing.JLabel lblestado;
    private javax.swing.JLabel lblinformacoes;
    private javax.swing.JLabel lblnomeempresa;
    private javax.swing.JLabel lblnumero;
    private javax.swing.JLabel lblpais;
    private javax.swing.JLabel lblsetor;
    private javax.swing.JLabel lblsetorempresa;
    private javax.swing.JLabel lblsite;
    private javax.swing.JLabel lblsobre;
    private javax.swing.JLabel lblvaga;
    private javax.swing.JPanel pnlContato;
    private javax.swing.JPanel pnlEndereco;
    private javax.swing.JPanel pnlVagas;
    // End of variables declaration//GEN-END:variables
}
