/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.telaPrincipal.view;

import br.com.ifba.usuario.entity.Usuario;
import br.com.ifba.usuario.view.LoginCandidatoView;
import br.com.ifba.vaga.controller.VagaController;
import br.com.ifba.vaga.view.VagaListar;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import br.com.ifba.usuario.controller.UsuarioCandidatoController;

/**
 *
 * @author Taila
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    
    private Usuario usuarioLogado;
    private VagaController vagaController;
    private UsuarioCandidatoController controller;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal(Usuario usuarioLogado, VagaController vagaController, UsuarioCandidatoController controller) {
        this.usuarioLogado = usuarioLogado;
        this.vagaController = vagaController;
        this.controller = controller;
    
        initComponents();
        estilizarTela();
    }

    
    private void estilizarTela() {
        //======JFRAME=====
        setTitle("Sistema de Vagas");
        setSize(530, 433);
        setLocationRelativeTo(null);
        setResizable(false);
        
        //==========HEADER=============
        jpnlTitulo.setBackground(Color.WHITE);
        
        lblTitulo.setText("Sistema de Vagas");
        lblTitulo.setFont(new Font("Arial", Font.BOLD, 18));
        lblTitulo.setForeground(Color.BLACK);
        
        btnCadastro.setText("Entrar");
        btnCadastro.setFocusPainted(false);
        
        
        //=======Fundo========
        getContentPane().setBackground(new Color(30, 63, 95));
        
        //=======CARD(jpnlVerVagas========
        jpnlVerVagas.setBackground(Color.WHITE);
        jpnlVerVagas.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
        
        btnListarVagas.setText("Ver vagas");
        btnListarVagas.setFont(new Font("Arial", Font.BOLD, 16));
        btnListarVagas.setForeground(Color.WHITE);
        btnListarVagas.setBackground(new Color(40, 130, 200));
        btnListarVagas.setFocusPainted(false);
        btnListarVagas.setBorderPainted(false);
        
        lblTextinho.setText("Encontre o seu próximo desafio!");
        lblTextinho.setFont(new Font("Arial", Font.PLAIN, 13));
        lblTextinho.setForeground(Color.DARK_GRAY);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnCadastro = new javax.swing.JButton();
        jpnlVerVagas = new javax.swing.JPanel();
        btnListarVagas = new javax.swing.JButton();
        lblTextinho = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("jLabel1");

        btnCadastro.setText("jButton1");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlTituloLayout = new javax.swing.GroupLayout(jpnlTitulo);
        jpnlTitulo.setLayout(jpnlTituloLayout);
        jpnlTituloLayout.setHorizontalGroup(
            jpnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlTituloLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastro)
                .addGap(16, 16, 16))
        );
        jpnlTituloLayout.setVerticalGroup(
            jpnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(btnCadastro))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnListarVagas.setText("jButton1");
        btnListarVagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarVagasActionPerformed(evt);
            }
        });

        lblTextinho.setText("jLabel1");

        javax.swing.GroupLayout jpnlVerVagasLayout = new javax.swing.GroupLayout(jpnlVerVagas);
        jpnlVerVagas.setLayout(jpnlVerVagasLayout);
        jpnlVerVagasLayout.setHorizontalGroup(
            jpnlVerVagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlVerVagasLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnListarVagas, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlVerVagasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTextinho, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jpnlVerVagasLayout.setVerticalGroup(
            jpnlVerVagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlVerVagasLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnListarVagas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTextinho, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jpnlVerVagas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 112, Short.MAX_VALUE))
            .addComponent(jpnlTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jpnlVerVagas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarVagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarVagasActionPerformed
        LoginCandidatoView tela = new LoginCandidatoView(controller);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListarVagasActionPerformed

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnListarVagas;
    private javax.swing.JPanel jpnlTitulo;
    private javax.swing.JPanel jpnlVerVagas;
    private javax.swing.JLabel lblTextinho;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
