/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.vaga.view;


import br.com.ifba.candidaturas.view.CandidaturaInscricao;
import br.com.ifba.usuario.entity.Usuario;
import br.com.ifba.usuario.entity.UsuarioEmpresa;
import br.com.ifba.vaga.controller.VagaController;
import br.com.ifba.vaga.entity.Vaga;
import javax.swing.JOptionPane;
/**
 *
 * @author Taila
 */
public class VagaDetalhes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VagaDetalhes.class.getName());

    // Atributos que armazenam os dados necessários para a tela funcionar
    private VagaController vagaController;
    private Usuario usuarioLogado;
    private Vaga  vaga; // Objeto da vaga específica que será exibida
    /**
     * Creates new form VagaDetalhes
     */
    public VagaDetalhes(Usuario usuarioLogado, VagaController vagaController, Vaga vaga) {
        this.usuarioLogado = usuarioLogado;
        this.vagaController = vagaController;
        this.vaga = vaga;

        
        initComponents();
        setLocationRelativeTo(null); // Centraliza a janela
        
        // Configura o JTextArea para quebrar o texto automaticamente quando chegar ao fim da largura
        txtDescricao.setLineWrap(true);
        txtDescricao.setWrapStyleWord(true);
        
        carregarDados(); //preenche os campos com a s informações da vaga
        configurarBotao(); //define se o botão dirá "editar" ou "candidatar-se"

    }
    
    private void carregarDados() {
        // Verifica se a vaga existe para evitar erro de NullPointerException
        if(vaga == null) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar dados da vaga.");
            return;
        }
        // StringBuilder é usado para concatenar textos de forma mais eficiente que String comum
        StringBuilder sb = new StringBuilder();
        
        sb.append("📝 DESCRIÇÃO DA VAGA\n\n");
        sb.append("Estamos em busca de um(a) ").append(vaga.getTitulo()).append("\n\n");
        
        // Pega os dados do objeto 'vaga' e adiciona ao texto
        sb.append("📌 Quantidade de vagas: ").append(vaga.getQuantidade()).append("\n");
        sb.append("💼 Modelo de contratação: ").append(vaga.getModelo()).append("\n");
        sb.append("🏢 Tipo de contratação: ").append(vaga.getTipo()).append("\n");
        sb.append("⏰ Período de contratação: ").append(vaga.getPeriodo()).append("\n");
        sb.append("📍 Localização: ").append(vaga.getLocalizacao().getCidade()).append("\n");
        sb.append("💰 Faixa salarial: ").append(vaga.getFaixaSalarial()).append("\n\n");
        
        sb.append("🚀 RESPONSABILIDADES\n");
        sb.append(vaga.getDescricao()).append("\n\n");
        
        sb.append("REQUISITOS\n");
        sb.append("A definir...\n\n"); // Pode preencher se tiver info
    
        sb.append("INFORMAÇÕES ADICIONAIS\n");
        sb.append("A definir...\n\n"); // Pode preencher se tiver info
        
        sb.append("ETAPAS DO PROCESSO\n");
        sb.append("A definir...\n\n"); 
        
        // Seta o texto final no componente JTextArea da tela
        txtDescricao.setText(sb.toString());
        txtDescricao.setCaretPosition(0);// Garante que a barra de rolagem comece no topo
        txtDescricao.setEditable(false);//Impede o usuário de apagar ou mudar o texto da descrição
    }
    
    /**
     * Define o comportamento visual do botão principal baseado no tipo de usuário
     */
    private void configurarBotao() {
        if(usuarioLogado instanceof UsuarioEmpresa){
            btnAcao.setText("Editar");
        }else {
            btnAcao.setText("Candidatar-se");
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        btnVoltar = new javax.swing.JButton();
        btnAcao = new javax.swing.JButton();
        lblTituloVaga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        lblTitulo.setText("Detalhes da Vaga");

        lblDescricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDescricao.setText("Descrição:");

        txtDescricao.setEditable(false);
        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        btnVoltar.setText("<---");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcaoActionPerformed(evt);
            }
        });

        lblTituloVaga.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        lblTituloVaga.setText("Titulo da vaga");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(lblDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblTituloVaga, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAcao, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblTitulo)))
                .addGap(18, 18, 18)
                .addComponent(lblTituloVaga, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(lblDescricao)
                        .addContainerGap(294, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAcao, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        new VagaListar(usuarioLogado, vagaController).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcaoActionPerformed
        if (usuarioLogado instanceof UsuarioEmpresa) {
            new VagaEditar(usuarioLogado, vagaController, vaga).setVisible(true);
            this.dispose();
        } else {
            //new CandidaturaInscricao(usuarioLogado, vaga).setVisible(true);
            //this.dispose();
        }
    }//GEN-LAST:event_btnAcaoActionPerformed
                                       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcao;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloVaga;
    private javax.swing.JTextArea txtDescricao;
    // End of variables declaration//GEN-END:variables
}
