/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.vaga.view;

import br.com.ifba.endereco.Endereco;
import br.com.ifba.infrastructure.spring.SpringContext;
import br.com.ifba.perfil.empresa.view.TelaApresentacaoEmpresa;
import br.com.ifba.usuario.entity.Usuario;
import br.com.ifba.usuario.sessao.SessaoUsuario;
import br.com.ifba.vaga.entity.Vaga;
import br.com.ifba.vaga.enums.ModeloContratacao;
import br.com.ifba.vaga.enums.TipoContratacao;
import br.com.ifba.vaga.enums.PeriodoContratacao;
import br.com.ifba.vaga.controller.VagaController;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
/**
 *
 * @author Taila
 */
public class VagaCadastrar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VagaCadastrar.class.getName());

    private final SessaoUsuario sessaoUsuario;
    private Usuario usuarioLogado;
    private VagaController vagaController;
    private ButtonGroup grupoStatus; // Agrupa os RadioButtons para que apenas um seja selecionado
    
    /**
     * Creates new form VagaCadastrar
     */
    @Autowired
    public VagaCadastrar(SessaoUsuario sessaoUsuario, VagaController vagaController) {
        this.sessaoUsuario = sessaoUsuario;
        this.vagaController = vagaController;
        this.usuarioLogado = usuarioLogado;

       
        initComponents();
        
        // Essencial para o template não sumir para o lado
        txtDescricao.setLineWrap(true);
        txtDescricao.setWrapStyleWord(true);
        
        configurarTela();
        carregarDescricaoPadrao();
        estilizarBotoes();  // Aplica cores e fontes personalizadas
    }
    
    /**
     * Configurações lógicas da interface gráfica
     */
    private void configurarTela() {
        this.setSize(677, 677);
        setLocationRelativeTo(null);

        // Lógica dos RadioButtons: impede que "Ativa" e "Encerrada" fiquem marcados ao mesmo tempo
        grupoStatus = new ButtonGroup();
        grupoStatus.add(rdAtiva);
        grupoStatus.add(jrdEncerrar);
        rdAtiva.setSelected(true);

        // Preenche os JComboBox (menus de seleção) com os valores definidos nos Enums
        jboxModeloContratação.setModel(
                new DefaultComboBoxModel<>(ModeloContratacao.values())
        );
        jboxTipo.setModel(
                new DefaultComboBoxModel<>(TipoContratacao.values())
        );
        jboxPeriodo.setModel(
                new DefaultComboBoxModel<>(PeriodoContratacao.values())
        );

    }
    
    /**
     * Define a estética dos botões (Cores, Fontes e Cursor)
     */
    private void estilizarBotoes() {

    // Botão Salvar
    btnSalvar.setBackground(new java.awt.Color(76, 175, 80)); // verde
    btnSalvar.setForeground(java.awt.Color.WHITE);
    btnSalvar.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
    btnSalvar.setFocusPainted(false);
    btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    // Botão Cancelar
    btnCancelar.setBackground(new java.awt.Color(244, 67, 54)); // vermelho
    btnCancelar.setForeground(java.awt.Color.WHITE);
    btnCancelar.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
    btnCancelar.setFocusPainted(false);
    btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
}

    /**
     * Insere um template no campo de descrição para facilitar o preenchimento da empresa
     */
    private void carregarDescricaoPadrao() {
        txtDescricao.setText(DESCRICAO_PADRAO);
    }
    // Template de texto constante
    private static final String DESCRICAO_PADRAO =
            
            "🚀 RESPONSABILIDADES\n" +
            "- \n\n" +
            
            "📌 REQUISITOS\n" +
            "- \n\n" +
            
            "ℹ️ INFORMAÇÕES ADICIONAIS\n" +
            "- \n\n" +
            
            "⏳ ETAPAS DO PROCESSO\n" +
            "- ";
            
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblTituloVaga = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        jboxModeloContratação = new javax.swing.JComboBox<>();
        jboxTipo = new javax.swing.JComboBox<>();
        lblTipo = new javax.swing.JLabel();
        lblPeriodo = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        scrollDescricao = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        lblStatus = new javax.swing.JLabel();
        rdAtiva = new javax.swing.JRadioButton();
        jrdEncerrar = new javax.swing.JRadioButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jboxPeriodo = new javax.swing.JComboBox<>();
        lblSalario = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtSalario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        lblTitulo.setText("Cadastro da Vaga");

        lblTituloVaga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTituloVaga.setText("título da vaga:");

        lblQuantidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQuantidade.setText("Quantidade de vagas:");

        lblModelo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblModelo.setText("Modelo de contratação:");

        jboxModeloContratação.setModel(new javax.swing.DefaultComboBoxModel<>(ModeloContratacao.values()));
        jboxModeloContratação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jboxModeloContrataçãoActionPerformed(evt);
            }
        });

        jboxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(TipoContratacao.values()));
        jboxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jboxTipoActionPerformed(evt);
            }
        });

        lblTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTipo.setText("Tipo de contratação:");

        lblPeriodo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPeriodo.setText("Período de Contratação:");

        lblDescricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDescricao.setText("Descrição:");

        lblEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEndereco.setText("Cidade da vaga:");

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        scrollDescricao.setViewportView(txtDescricao);

        lblStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStatus.setText("Status da Vaga:");

        rdAtiva.setText("Ativa");
        rdAtiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdAtivaActionPerformed(evt);
            }
        });

        jrdEncerrar.setText("Encerrada");
        jrdEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdEncerrarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jboxPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(PeriodoContratacao.values()));

        lblSalario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSalario.setText("Faixa salarial:");

        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });

        txtSalario.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblQuantidade)
                            .addComponent(lblTituloVaga)
                            .addComponent(lblModelo)
                            .addComponent(lblTipo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jboxModeloContratação, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jboxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSalario)
                            .addComponent(lblPeriodo)
                            .addComponent(lblEndereco))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jboxPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addGap(127, 127, 127)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStatus)
                        .addGap(38, 38, 38)
                        .addComponent(rdAtiva, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jrdEncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(163, 163, 163))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitulo)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloVaga)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblQuantidade)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelo)
                    .addComponent(jboxModeloContratação, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jboxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeriodo)
                    .addComponent(jboxPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndereco)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalario)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblDescricao)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(rdAtiva)
                    .addComponent(jrdEncerrar))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar))
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdAtivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdAtivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdAtivaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
    /**
     * Ação principal: Coleta os dados da tela e salva no banco de dados
     */
        try {
            // 1. Validações básicas de campos vazios
            if (txtTitulo.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Informe o título da vaga.");
                return;
            }
        
            if (txtQuantidade.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Informe a quantidade de vagas.");
                return;
            }

            // 2. Criação da entidade Vaga e atribuição dos valores
            Vaga vaga = new Vaga();
            vaga.setTitulo(txtTitulo.getText());
            vaga.setQuantidade(Integer.parseInt(txtQuantidade.getText().trim()));
            vaga.setModelo((ModeloContratacao) jboxModeloContratação.getSelectedItem());
            vaga.setTipo((TipoContratacao) jboxTipo.getSelectedItem());
            vaga.setPeriodo((PeriodoContratacao) jboxPeriodo.getSelectedItem());
            vaga.setDescricao(txtDescricao.getText());
            vaga.setStatus(rdAtiva.isSelected());
        
            // 3. Tratamento seguro do salário (remove pontos/vírgulas se houver)
            String salarioStr = txtSalario.getText().replaceAll("[^0-9]", ""); 
            vaga.setFaixaSalarial(salarioStr.isEmpty() ? 0L : Long.parseLong(salarioStr));
        
            // 4. Criação e associação do objeto de endereço
            Endereco endereco = new Endereco();
            endereco.setCidade(txtEndereco.getText());
            endereco.setEstado("Não informado");
            endereco.setPais("Brasil");
            vaga.setLocalizacao(endereco);

            // 5. Persistência no banco de dados
            vagaController.save(vaga);
        
            JOptionPane.showMessageDialog(this, "Vaga cadastrada com sucesso!");
        
            // 6. Fecha tela atual e volta para a listagem
            new VagaListar(sessaoUsuario, vagaController).setVisible(true);
            TelaApresentacaoEmpresa telaApres = SpringContext.getBean(TelaApresentacaoEmpresa.class);
            // Se você tiver o perfil salvo na sessão, pode recarregar aqui
             telaApres.atualizarTela();
            this.dispose();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Erro: Os campos 'Quantidade' e 'Salário' devem conter apenas números.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro inesperado ao salvar: " + e.getMessage());
        }

    }

    private void limparCampos() {
        txtTitulo.setText("");
        txtQuantidade.setText("");
        txtEndereco.setText("");
        rdAtiva.setSelected(true);
        carregarDescricaoPadrao();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void jrdEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdEncerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdEncerrarActionPerformed

    private void jboxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jboxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jboxTipoActionPerformed

    private void jboxModeloContrataçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jboxModeloContrataçãoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jboxModeloContrataçãoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
         new VagaListar(sessaoUsuario, vagaController).setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<ModeloContratacao> jboxModeloContratação;
    private javax.swing.JComboBox<PeriodoContratacao> jboxPeriodo;
    private javax.swing.JComboBox<TipoContratacao> jboxTipo;
    private javax.swing.JRadioButton jrdEncerrar;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPeriodo;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloVaga;
    private javax.swing.JRadioButton rdAtiva;
    private javax.swing.JScrollPane scrollDescricao;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
