/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.vaga.view;

import br.com.ifba.endereco.Endereco;
import br.com.ifba.usuario.entity.Usuario;
import br.com.ifba.vaga.entity.Vaga;
import br.com.ifba.vaga.enums.ModeloContratacao;
import br.com.ifba.vaga.enums.TipoContratacao;
import br.com.ifba.vaga.enums.PeriodoContratacao;
import br.com.ifba.vaga.service.VagaService;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Taila
 */
public class VagaCadastrar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VagaCadastrar.class.getName());

    private Usuario usuarioLogado;
    private VagaService vagaService;
    private ButtonGroup grupoStatus; // Agrupa os RadioButtons para que apenas um seja selecionado
    
    /**
     * Creates new form VagaCadastrar
     */
    public VagaCadastrar(Usuario usuarioLogado, VagaService vagaService) {
        this.usuarioLogado = usuarioLogado;
        this.vagaService = vagaService;


        initComponents();
        configurarTela();
        carregarDescricaoPadrao();
        estilizarBotoes();  // Aplica cores e fontes personalizadas
    }
    
    /**
     * Configurações lógicas da interface gráfica
     */
    private void configurarTela() {
        setLocationRelativeTo(null);

        // Lógica dos RadioButtons: impede que "Ativa" e "Encerrada" fiquem marcados ao mesmo tempo
        grupoStatus = new ButtonGroup();
        grupoStatus.add(rdAtiva);
        grupoStatus.add(jrdEncerrar);
        rdAtiva.setSelected(true);

        // Preenche os JComboBox (menus de seleção) com os valores definidos nos Enums
        jboxModeloContratação.setModel(
                new DefaultComboBoxModel<>(ModeloContratacao.values())
        );
        jboxTipo.setModel(
                new DefaultComboBoxModel<>(TipoContratacao.values())
        );
        jboxPeriodo.setModel(
                new DefaultComboBoxModel<>(PeriodoContratacao.values())
        );

    }
    
    /**
     * Define a estética dos botões (Cores, Fontes e Cursor)
     */
    private void estilizarBotoes() {

    // Botão Salvar
    btnSalvar.setBackground(new java.awt.Color(76, 175, 80)); // verde
    btnSalvar.setForeground(java.awt.Color.WHITE);
    btnSalvar.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
    btnSalvar.setFocusPainted(false);
    btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    // Botão Cancelar
    btnCancelar.setBackground(new java.awt.Color(244, 67, 54)); // vermelho
    btnCancelar.setForeground(java.awt.Color.WHITE);
    btnCancelar.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
    btnCancelar.setFocusPainted(false);
    btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
}

    /**
     * Insere um template no campo de descrição para facilitar o preenchimento da empresa
     */
    private void carregarDescricaoPadrao() {
        txtDescricao.setText(DESCRICAO_PADRAO);
    }
    // Template de texto constante
    private static final String DESCRICAO_PADRAO = 
            "📝 DESCRIÇÃO DA VAGA\n\n" +
            "Estamos em busca de um(a) ____________________________\n\n" +
    
            "📍 Local: __________\n" +
            "🕘 Modelo de trabalho: __________\n" +
            "💼 Tipo de contratação: __________\n\n" +
            "FAIXA SALARIAL: ____________\n\n" +
            
            "🚀 RESPONSABILIDADES\n\n" +
            
            "REQUISITOS\n\n" +
            
            "INFORMAÇÕES ADICIONAIS\n\n" +
            
            "ETAPAS DO PROCESSO\n\n";
            
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblTituloVaga = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        jboxModeloContratação = new javax.swing.JComboBox<>();
        jboxTipo = new javax.swing.JComboBox<>();
        lblTipo = new javax.swing.JLabel();
        lblPeriodo = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        scrollDescricao = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        lblStatus = new javax.swing.JLabel();
        rdAtiva = new javax.swing.JRadioButton();
        jrdEncerrar = new javax.swing.JRadioButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jboxPeriodo = new javax.swing.JComboBox<>();
        txtTitulo = new java.awt.TextField();
        txtQuantidade = new java.awt.TextField();
        txtEndereco = new java.awt.TextField();
        lblSalario = new javax.swing.JLabel();
        txtSalario = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        lblTitulo.setText("Cadastro da Vaga");

        lblTituloVaga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTituloVaga.setText("título da vaga:");

        lblQuantidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQuantidade.setText("Quantidade de vagas:");

        lblModelo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblModelo.setText("Modelo de contratação:");

        jboxModeloContratação.setModel(new javax.swing.DefaultComboBoxModel<>(ModeloContratacao.values()));
        jboxModeloContratação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jboxModeloContrataçãoActionPerformed(evt);
            }
        });

        jboxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(TipoContratacao.values()));
        jboxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jboxTipoActionPerformed(evt);
            }
        });

        lblTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTipo.setText("Tipo de contratação:");

        lblPeriodo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPeriodo.setText("Período de Contratação:");

        lblDescricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDescricao.setText("Descrição:");

        lblEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEndereco.setText("Cidade da vaga:");

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        scrollDescricao.setViewportView(txtDescricao);

        lblStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStatus.setText("Status da Vaga:");

        rdAtiva.setText("Ativa");
        rdAtiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdAtivaActionPerformed(evt);
            }
        });

        jrdEncerrar.setText("Encerrada");
        jrdEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdEncerrarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jboxPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(PeriodoContratacao.values()));

        txtTitulo.setText("");
        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        txtQuantidade.setText("");
        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });

        txtEndereco.setText("");
        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });

        lblSalario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSalario.setText("Faixa salarial:");

        txtSalario.setText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblQuantidade)
                            .addComponent(lblTituloVaga)
                            .addComponent(lblModelo)
                            .addComponent(lblTipo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jboxModeloContratação, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jboxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSalario)
                            .addComponent(lblPeriodo)
                            .addComponent(lblEndereco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jboxPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdAtiva, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrdEncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvar)
                        .addGap(64, 64, 64)
                        .addComponent(btnCancelar)
                        .addGap(163, 163, 163))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitulo)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloVaga)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblQuantidade)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelo)
                    .addComponent(jboxModeloContratação, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jboxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeriodo)
                    .addComponent(jboxPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEndereco)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSalario)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblDescricao)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(rdAtiva)
                    .addComponent(jrdEncerrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar))
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdAtivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdAtivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdAtivaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
    /**
     * Ação principal: Coleta os dados da tela e salva no banco de dados
     */
        try {
            if (txtTitulo.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Informe o título da vaga.");
                return;
            }
            
            if (txtQuantidade.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Informe a quantidade de vagas.");
                return;
            }

            // Validação e conversão numérica da quantidade
            int quantidade = Integer.parseInt(txtQuantidade.getText());

            // Criação da entidade Vaga e atribuição dos valores da tela
            Vaga vaga = new Vaga();
            vaga.setTitulo(txtTitulo.getText());
            vaga.setQuantidade(quantidade);
            vaga.setModelo((ModeloContratacao) jboxModeloContratação.getSelectedItem());
            vaga.setTipo((TipoContratacao) jboxTipo.getSelectedItem());
            vaga.setPeriodo((PeriodoContratacao) jboxPeriodo.getSelectedItem());
            vaga.setDescricao(txtDescricao.getText());
            vaga.setStatus(rdAtiva.isSelected());
            
            // Tratamento específico para o salário (deve ser numérico)
            try {
                long faixaSalarial = Long.parseLong(txtSalario.getText());
                vaga.setFaixaSalarial(faixaSalarial);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Faixa salarial deve ser numérica!");
                return;
            }
            
            // Criação do objeto de endereço associado à vaga
            Endereco endereco = new Endereco();
            endereco.setCidade(txtEndereco.getText());
            endereco.setEstado("Não informado");
            endereco.setPais("Brasil");

            vaga.setLocalizacao(endereco);


            vagaService.save(vaga);
            
            // Fecha tela e volta para listagem
            new VagaListar(usuarioLogado, vagaService).setVisible(true);
            this.dispose();

            JOptionPane.showMessageDialog(this, "Vaga cadastrada com sucesso!");
            limparCampos();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Quantidade deve ser numérica.");
        }
       
    }

    private void limparCampos() {
        txtTitulo.setText("");
        txtQuantidade.setText("");
        txtEndereco.setText("");
        rdAtiva.setSelected(true);
        carregarDescricaoPadrao();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void jrdEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdEncerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdEncerrarActionPerformed

    private void jboxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jboxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jboxTipoActionPerformed

    private void jboxModeloContrataçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jboxModeloContrataçãoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jboxModeloContrataçãoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
         new VagaListar(usuarioLogado, vagaService).setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed

    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed

    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed

    }//GEN-LAST:event_txtTituloActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<ModeloContratacao> jboxModeloContratação;
    private javax.swing.JComboBox<PeriodoContratacao> jboxPeriodo;
    private javax.swing.JComboBox<TipoContratacao> jboxTipo;
    private javax.swing.JRadioButton jrdEncerrar;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPeriodo;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloVaga;
    private javax.swing.JRadioButton rdAtiva;
    private javax.swing.JScrollPane scrollDescricao;
    private javax.swing.JTextArea txtDescricao;
    private java.awt.TextField txtEndereco;
    private java.awt.TextField txtQuantidade;
    private java.awt.TextField txtSalario;
    private java.awt.TextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
