/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.perfil.candidato.view;

import br.com.ifba.perfil.candidato.controller.PerfilCandidatoIController;
import br.com.ifba.perfil.entity.Idioma;
import java.awt.FlowLayout;
import java.util.Set;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author USER
 */

@Component
@Scope("prototype")
public class TelaExcluirIdioma extends javax.swing.JFrame {
    
    @Autowired
    private PerfilCandidatoIController perfilCandidatoController;
    private Long id;
    
    public void setDados(Long id) {
        this.id = id;
        carregarIdiomas();
    }
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaExcluirIdioma.class.getName());

    /**
     * Creates new form TelaExcluirIdioma
     */
    public TelaExcluirIdioma() {
        initComponents();
        
        setSize(500, 600);      // largura x altura
        setLocationRelativeTo(null); // centraliza na tela
        setResizable(false);   // impede redimensionamento
    }
    
    private TelaApresentacaoCandidato telaApresentacao;

    public void setTelaApresentacaoCandidato(TelaApresentacaoCandidato tela) {
        this.telaApresentacao = tela;
    }
    
    private void carregarIdiomas() {
    pnlListar.removeAll();
    // Define layout vertical para que cada item fique em uma linha
    pnlListar.setLayout(new javax.swing.BoxLayout(pnlListar, javax.swing.BoxLayout.Y_AXIS));

    Set<Idioma> idiomas = perfilCandidatoController.findAllIdioma(id);

    if (idiomas != null) {
        for (Idioma idi : idiomas) { 
            pnlListar.add(criarLinha(idi)); 
        }
    }

    // FORÇA A ATUALIZAÇÃO VISUAL (Essencial para as informações aparecerem)
    pnlListar.revalidate(); 
    pnlListar.repaint();
    }
    
    private JPanel criarLinha(Idioma idioma) {
    JPanel linha = new JPanel(new FlowLayout(FlowLayout.LEFT));
    JLabel lbl = new JLabel(idioma.getIdioma() + " - Nível: " + idioma.getNivel());
    JButton btnExcluir = new JButton("Excluir");

    btnExcluir.addActionListener(e -> {
        if (JOptionPane.showConfirmDialog(this, "Excluir idioma?") == JOptionPane.YES_OPTION) {
            perfilCandidatoController.deleteByIdIdioma(idioma.getId()); // Método correto
            if (this.telaApresentacao != null) this.telaApresentacao.recarregarPerfil();
            carregarIdiomas(); // Método de recarga da sua tela
        }
    });
    linha.add(lbl); 
    linha.add(btnExcluir);
    return linha;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlListar = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("IDIOMA");

        javax.swing.GroupLayout pnlListarLayout = new javax.swing.GroupLayout(pnlListar);
        pnlListar.setLayout(pnlListarLayout);
        pnlListarLayout.setHorizontalGroup(
            pnlListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlListarLayout.setVerticalGroup(
            pnlListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addGap(93, 93, 93)
                        .addComponent(jLabel1)
                        .addGap(0, 180, Short.MAX_VALUE))
                    .addComponent(pnlListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnVoltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        if (this.telaApresentacao != null) {
            // Recarrega o perfil para que as exclusões/edições apareçam na tela principal
            this.telaApresentacao.recarregarPerfil();
            this.telaApresentacao.setVisible(true);
        }
        
        this.dispose(); // Fecha a tela de exclusão/edição
    }//GEN-LAST:event_btnVoltarActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlListar;
    // End of variables declaration//GEN-END:variables
}
