/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.perfil.candidato.view;

import br.com.ifba.perfil.candidato.controller.PerfilCandidatoIController;
import br.com.ifba.perfil.entity.Formacao;
import java.awt.FlowLayout;
import java.util.Set;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author USER
 */

@Component
@Scope("prototype")
public class TelaExcluirFormacao extends javax.swing.JFrame {
    
    @Autowired
    private PerfilCandidatoIController perfilCandidatoController;
    private Long id;
    
    
    public void setDados(Long id) {
        this.id = id;
        carregarFormações();
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaExcluirFormacao.class.getName());

    /**
     * Creates new form TelaExcluirFormacao
     */
    public TelaExcluirFormacao() {
        initComponents();
    }
    
    private void carregarFormações() {

        pnlListar.removeAll();

        Set<Formacao> formacoes =
                perfilCandidatoController.findAllFormacao(id);

        for (Formacao form : formacoes) {
            pnlListar.add(criarLinha(form));
        }

        pnlListar.revalidate();
        pnlListar.repaint();
    }
    
    private JPanel criarLinha(Formacao form) {
        JPanel linha = new JPanel();
        linha.setLayout(new FlowLayout(FlowLayout.LEFT));
        
        JLabel lbl = new JLabel(
                form.getInstituicao() + " " +
                        form.getNomeDocurso() + " " +
                        form.getDataInicial() + " " +
                        form.getDataFinal() 
        );
        
        JButton btnExcluir = new JButton("Excluir");
        
        btnExcluir.addActionListener(e -> {
            perfilCandidatoController.deletedByIdFormacao(form.getId());
            carregarFormações();
        });
        
        linha.add(lbl);
        linha.add(btnExcluir);
        
        return linha;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFormacao = new javax.swing.JLabel();
        pnlListar = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFormacao.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblFormacao.setText("FORMAÇÕES");

        javax.swing.GroupLayout pnlListarLayout = new javax.swing.GroupLayout(pnlListar);
        pnlListar.setLayout(pnlListarLayout);
        pnlListarLayout.setHorizontalGroup(
            pnlListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlListarLayout.setVerticalGroup(
            pnlListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(lblFormacao)
                .addContainerGap(155, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFormacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFormacao;
    private javax.swing.JPanel pnlListar;
    // End of variables declaration//GEN-END:variables
}
