/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.perfil.candidato.view;

import br.com.ifba.perfil.candidato.controller.PerfilCandidatoIController;
import br.com.ifba.perfil.entity.PerfilCandidato;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author USER
 */

@Component
@Scope ("prototype")
public class TelaEditarSobreMim extends javax.swing.JFrame {
    
    @Autowired
    private PerfilCandidatoIController perfilcandidatocontroller;
    
    private TelaApresentacao telaapresentacao;
    private PerfilCandidato perfilcandidato;
    private Long idPerfil;
    
    public void setTelaApresentacao(TelaApresentacao telaapresentacao){
        this.telaapresentacao = telaapresentacao;
    }
    
    public void setPerfilCandidato(PerfilCandidato perfilcandidato){
        this.perfilcandidato = perfilcandidato;   
    }
    
    public void setDados(Long idPerfil, String textoAtual) {
        this.idPerfil = idPerfil;
        txtsobremim.setText(textoAtual);
    }

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaEditarSobreMim.class.getName());

    /**
     * Creates new form TelaEditarCandidato
     */
    public TelaEditarSobreMim() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtsobremim = new javax.swing.JTextField();
        lblsobremim = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblsobremim.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblsobremim.setText("SOBRE MIM");

        btnsave.setText("SALVAR");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnsave)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtsobremim, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblsobremim, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblsobremim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsobremim, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnsave)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        String novotexto = txtsobremim.getText();
        
        perfilcandidatocontroller.atualizarSobreMim(idPerfil, novotexto);
        JOptionPane.showMessageDialog(this, "Campo 'sobre mim' atualizado com sucesso");
        
        telaapresentacao.atualizarSobreMim(novotexto);
        telaapresentacao.setVisible(true);
        this.dispose();
    
    }//GEN-LAST:event_btnsaveActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel lblsobremim;
    private javax.swing.JTextField txtsobremim;
    // End of variables declaration//GEN-END:variables
}
