/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.perfil.candidato.view;

import br.com.ifba.infrastructure.spring.SpringContext;
import br.com.ifba.perfil.candidato.controller.PerfilCandidatoController;
import br.com.ifba.perfil.entity.Idioma;
import java.awt.FlowLayout;
import java.util.Set;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author USER
 */

@Component
@Scope("prototype")
public class TelaEditarIdoma extends javax.swing.JFrame {
    
    @Autowired
    private PerfilCandidatoController perfilcandidatocontroller;
    
    private Long id;
    private TelaApresentacaoCandidato telaApresentacao;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaEditarIdoma.class.getName());

    /**
     * Creates new form TelaEditarIdoma
     */
    public TelaEditarIdoma() {
        initComponents();
        this.setLocationRelativeTo(null);
        // Define layout vertical para o painel de listagem
        pnlListar.setLayout(new javax.swing.BoxLayout(pnlListar, javax.swing.BoxLayout.Y_AXIS));
    
    }
    
    public void setDados(Long id){
        this.id = id;
        carregarIdioma();
    }
    
    private void carregarIdioma(){
        pnlListar.removeAll();
        
        Set<Idioma> idioma = perfilcandidatocontroller.findAllIdioma(id);
        
        if(idioma != null){
            for (Idioma idi : idioma){
                pnlListar.add(criarLinha(idi));
            }
        }
        
        pnlListar.revalidate();
        pnlListar.repaint();
    }
    
    private JPanel criarLinha(Idioma idi) {
        JPanel linha = new JPanel(new FlowLayout(FlowLayout.LEFT));
        linha.setBorder(BorderFactory.createEtchedBorder());

        JLabel lbl = new JLabel(idi.getIdioma() + "Nível " + idi.getNivel());
        JButton btnEditar = new JButton("Editar");
        
        // Ação do Botão Editar
        btnEditar.addActionListener(e -> {
            TelaAdicionarIdioma telaForm = SpringContext.getBean(TelaAdicionarIdioma.class);
    
            // Passamos o ID do perfil para que o service saiba onde procurar
            telaForm.setDados(this.id); 
    
            // IMPORTANTE: Passe o objeto 'comp' que veio da lista, sem modificá-lo
            telaForm.preencherDados(idi); 
    
            telaForm.setTelaApresentacaoCandidato(this.telaApresentacao);
            telaForm.setVisible(true);
            this.dispose();
        });

        linha.add(lbl);
        linha.add(btnEditar);
        return linha;
    }
    
    public void setTelaApresentacaoCandidato(TelaApresentacaoCandidato tela) {
        this.telaApresentacao = tela;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIdioma = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        pnlListar = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblIdioma.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblIdioma.setText("IDIOMA");

        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlListarLayout = new javax.swing.GroupLayout(pnlListar);
        pnlListar.setLayout(pnlListarLayout);
        pnlListarLayout.setHorizontalGroup(
            pnlListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );
        pnlListarLayout.setVerticalGroup(
            pnlListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnVoltar)
                        .addGap(70, 70, 70)
                        .addComponent(lblIdioma))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdioma)
                    .addComponent(btnVoltar))
                .addGap(18, 18, 18)
                .addComponent(pnlListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        if (this.telaApresentacao != null) {
            this.telaApresentacao.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblIdioma;
    private javax.swing.JPanel pnlListar;
    // End of variables declaration//GEN-END:variables
}
