/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.perfil.candidato.view;

import br.com.ifba.infrastructure.spring.SpringContext;
import br.com.ifba.perfil.candidato.controller.PerfilCandidatoController;
import br.com.ifba.perfil.entity.Formacao;
import java.awt.FlowLayout;
import java.util.Set;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author USER
 */
@Component
@Scope("prototype")
public class TelaEditarFormacao extends javax.swing.JFrame {
    
    @Autowired
    private PerfilCandidatoController perfilcandidatocontroller;
    
    private Long id;
    private TelaApresentacaoCandidato telaApresentacao;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaEditarFormacao.class.getName());

    /**
     * Creates new form TelaEditarFormacao
     */
    public TelaEditarFormacao() {
        initComponents();
        this.setLocationRelativeTo(null);
        // Define layout vertical para o painel de listagem
        pnlListar.setLayout(new javax.swing.BoxLayout(pnlListar, javax.swing.BoxLayout.Y_AXIS));
    }
    
    public void setDados(Long id){
        this.id = id;
        carregarFormacao();
    }
    
    private void carregarFormacao(){
        pnlListar.removeAll();
        
        Set<Formacao> formacao = perfilcandidatocontroller.findAllFormacao(id);
        
        if(formacao != null){
            for (Formacao form : formacao){
                pnlListar.add(criarLinha(form));
            }
        }
        
        pnlListar.revalidate();
        pnlListar.repaint();
    }
    
    private JPanel criarLinha(Formacao form) {
        JPanel linha = new JPanel(new FlowLayout(FlowLayout.LEFT));
        linha.setBorder(BorderFactory.createEtchedBorder());

        JLabel lbl = new JLabel(form.getNomeDocurso() + " na " + form.getInstituicao());
        JButton btnEditar = new JButton("Editar");
        
        // Ação do Botão Editar
        btnEditar.addActionListener(e -> {
            TelaAdicionarFormacao telaForm = SpringContext.getBean(TelaAdicionarFormacao.class);
            telaForm.setDados(id); // ID do Perfil
            telaForm.preencherDados(form); // Passe o objeto 'form' completo [cite: 113]
            telaForm.setTelaApresentacaoCandidato(this.telaApresentacao);
            telaForm.setVisible(true);
            this.dispose();
        });

        linha.add(lbl);
        linha.add(btnEditar);
        return linha;
    }
    
    public void setTelaApresentacaoCandidato(TelaApresentacaoCandidato tela) {
        this.telaApresentacao = tela;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        lblFormacao = new javax.swing.JLabel();
        pnlListar = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblFormacao.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblFormacao.setText("FORMAÇÃO ACADÊMICA");

        javax.swing.GroupLayout pnlListarLayout = new javax.swing.GroupLayout(pnlListar);
        pnlListar.setLayout(pnlListarLayout);
        pnlListarLayout.setHorizontalGroup(
            pnlListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        pnlListarLayout.setVerticalGroup(
            pnlListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addGap(47, 47, 47)
                        .addComponent(lblFormacao)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(lblFormacao))
                .addGap(18, 18, 18)
                .addComponent(pnlListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        if (this.telaApresentacao != null) {
            this.telaApresentacao.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblFormacao;
    private javax.swing.JPanel pnlListar;
    // End of variables declaration//GEN-END:variables
}
