/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.perfil.candidato.view;

import br.com.ifba.perfil.candidato.controller.PerfilCandidatoIController;
import br.com.ifba.perfil.entity.Competencia;
import br.com.ifba.perfil.entity.Formacao;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author USER
 */
@Component
@Scope("prototype")
public class TelaAdicionarCompetencia extends javax.swing.JFrame {
    
    @Autowired
    private PerfilCandidatoIController perfilcandidatocontroller;
    
    private Long idPerfil;
    private Competencia competenciaEmEdicao; // ✅ única fonte da verdade
    private TelaApresentacaoCandidato tela;

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaAdicionarCompetencia.class.getName());

    /**
     * Creates new form TelaEditarCompetencia
     */
    public TelaAdicionarCompetencia() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
     public void setDados(Long idPerfil) {
        this.idPerfil = idPerfil;
    }

    public void setTelaApresentacaoCandidato(TelaApresentacaoCandidato tela) {
        this.tela = tela;
    }

    //MÉTODO PARA PREENCHER OS CAMPOS NA EDIÇÃO
    public void preencherDados(Competencia comp) {
        this.competenciaEmEdicao = comp;
        
    txtTitulo.setText(comp.getTitulo());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCompetencia = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        btnsalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCompetencia.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblCompetencia.setText("COMPETÊNCIAS");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTitulo.setText("TÍTULO");

        txtTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnsalvar.setText("SALVAR");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(lblCompetencia))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btnsalvar)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCompetencia)
                .addGap(45, 45, 45)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(btnsalvar)
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        // TODO add your handling code here:
        String titulo = txtTitulo.getText().trim();

    try {
        Competencia comp;
        
        // Se houver uma competência em edição, usamos ela (mesma representação)
        if (this.competenciaEmEdicao != null) {
            comp = this.competenciaEmEdicao;
        } else {
            comp = new Competencia();
        }

        comp.setTitulo(titulo);

        if (this.competenciaEmEdicao != null) {
            // Chama o update para sincronizar a instância existente
            perfilcandidatocontroller.updateCompetencia(idPerfil, comp);
        } else {
            // Chama o add para nova competência
            perfilcandidatocontroller.addCompetencia(idPerfil, comp);
        }

        JOptionPane.showMessageDialog(this, "Salvo com sucesso!");
        
        if (this.tela != null) {
            this.tela.recarregarPerfil(); 
        }
        this.dispose();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
    }
    }//GEN-LAST:event_btnsalvarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsalvar;
    private javax.swing.JLabel lblCompetencia;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
