/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.perfil.candidato.view;

import br.com.ifba.infrastructure.spring.SpringContext;
import br.com.ifba.perfil.candidato.controller.PerfilCandidatoIController;
import br.com.ifba.perfil.entity.PerfilCandidato;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author USER
 */

@Component
@Scope("prototype")
public class TelaApresentacao extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaApresentacao.class.getName());

    @Autowired
    private PerfilCandidatoIController perfilcandidatocontroller;
    private PerfilCandidato perfilcandidato;
    
    public void atualizarSobreMim(String texto) {
        lbldescricionaboutme.setText(texto);
        perfilcandidato.setSobre(texto);
    }

    public void setPerfilCandidato(PerfilCandidato perfil) {
    this.perfilcandidato = perfil;
    carregarExperiencias();
    }
    /**
     * Creates new form TelaApresentacao
     */
    public TelaApresentacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnpainelcentral = new javax.swing.JPanel();
        lblcompletedname = new javax.swing.JLabel();
        lblaboutme = new javax.swing.JLabel();
        lbldescricionaboutme = new javax.swing.JLabel();
        btncontact = new javax.swing.JButton();
        pnlexperience = new javax.swing.JPanel();
        pnlexpirenceinterne = new javax.swing.JPanel();
        lbltitulo = new javax.swing.JLabel();
        lblempresa = new javax.swing.JLabel();
        lbldatestart = new javax.swing.JLabel();
        lbldateend = new javax.swing.JLabel();
        lblexpirence = new javax.swing.JLabel();
        btneditaboutme = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btninsert = new javax.swing.JButton();
        lblformation = new javax.swing.JLabel();
        pnlformation = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblinstituicion = new javax.swing.JLabel();
        lblkingformation = new javax.swing.JLabel();
        lblcoursename = new javax.swing.JLabel();
        lbldatestartformation = new javax.swing.JLabel();
        lbldateendformation = new javax.swing.JLabel();
        lblcompetence = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnadicionarformacao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnpainelcentral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcompletedname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpnpainelcentral.add(lblcompletedname, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 6, 410, 40));

        lblaboutme.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblaboutme.setText("SOBRE MIM");
        jpnpainelcentral.add(lblaboutme, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 70, 10));

        lbldescricionaboutme.setBackground(new java.awt.Color(255, 255, 255));
        lbldescricionaboutme.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbldescricionaboutme.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                lbldescricionaboutmeComponentAdded(evt);
            }
        });
        jpnpainelcentral.add(lbldescricionaboutme, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 420, 70));

        btncontact.setBackground(new java.awt.Color(204, 0, 153));
        btncontact.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btncontact.setForeground(new java.awt.Color(255, 255, 255));
        btncontact.setText("INFORMAÇÕES DE CONTATO");
        jpnpainelcentral.add(btncontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        pnlexperience.setBackground(new java.awt.Color(255, 255, 255));
        pnlexperience.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlexperience.setLayout(new javax.swing.BoxLayout(pnlexperience, javax.swing.BoxLayout.LINE_AXIS));

        pnlexpirenceinterne.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltitulo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlexpirenceinterne.add(lbltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 5, 380, 20));

        lblempresa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlexpirenceinterne.add(lblempresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 280, 20));

        lbldatestart.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlexpirenceinterne.add(lbldatestart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 140, 20));

        lbldateend.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlexpirenceinterne.add(lbldateend, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 130, 20));

        pnlexperience.add(pnlexpirenceinterne);

        jpnpainelcentral.add(pnlexperience, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 420, 110));

        lblexpirence.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblexpirence.setText("EXPERIÊNCIAS");
        jpnpainelcentral.add(lblexpirence, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        btneditaboutme.setBackground(new java.awt.Color(242, 242, 242));
        btneditaboutme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/editar.png"))); // NOI18N
        btneditaboutme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditaboutmeActionPerformed(evt);
            }
        });
        jpnpainelcentral.add(btneditaboutme, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 30, 20));

        jButton1.setBackground(new java.awt.Color(242, 242, 242));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/editar.png"))); // NOI18N
        jpnpainelcentral.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 30, 20));

        btninsert.setBackground(new java.awt.Color(242, 242, 242));
        btninsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cadastrar.png"))); // NOI18N
        btninsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertActionPerformed(evt);
            }
        });
        jpnpainelcentral.add(btninsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 30, 20));

        lblformation.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblformation.setText("FORMAÇÕES ");
        jpnpainelcentral.add(lblformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        pnlformation.setBackground(new java.awt.Color(255, 255, 255));
        pnlformation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlformation.setLayout(new javax.swing.BoxLayout(pnlformation, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblinstituicion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lblinstituicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 20));

        lblkingformation.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lblkingformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, 20));

        lblcoursename.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lblcoursename, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 250, 20));

        lbldatestartformation.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lbldatestartformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 120, 20));

        lbldateendformation.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lbldateendformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 120, 20));

        pnlformation.add(jPanel1);

        jpnpainelcentral.add(pnlformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 420, 120));

        lblcompetence.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblcompetence.setText("COMPETÊNCIAS");
        jpnpainelcentral.add(lblcompetence, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpnpainelcentral.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 410, 110));

        btnadicionarformacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cadastrar.png"))); // NOI18N
        jpnpainelcentral.add(btnadicionarformacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 337, -1, 20));

        getContentPane().add(jpnpainelcentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 420, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbldescricionaboutmeComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_lbldescricionaboutmeComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lbldescricionaboutmeComponentAdded

    private void btneditaboutmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditaboutmeActionPerformed
        // TODO add your handling code here:
        TelaEditarSobreMim tela = SpringContext.getBean(TelaEditarSobreMim.class);

        tela.setDados(
        perfilcandidato.getId(),
        perfilcandidato.getSobre()
        );

        tela.setTelaApresentacao(this);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btneditaboutmeActionPerformed

    private void btninsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertActionPerformed
        // TODO add your handling code here:
         TelaEditarExperiencia tela =
        SpringContext.getBean(TelaEditarExperiencia.class);

        tela.setDados(perfilcandidato.getId());
        tela.setTelaApresentacao(this);

        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btninsertActionPerformed

    public void recarregarPerfil() {
    PerfilCandidato atualizado =
        perfilcandidatocontroller.findByUsuarioPerfil_Nome(
            perfilcandidato.getUsuarioPerfil().getNome()
        );

    setPerfilCandidato(atualizado);
    }

    private void carregarFormacoes() {

    pnlformation.removeAll();

    perfilcandidato.getFormacaoAcademica().forEach(f -> {

        JPanel painel = new JPanel();
        painel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLabel lblInstituicao = new JLabel(f.getInstituicao());
        JLabel lblCurso = new JLabel(f.getNomeDocurso());
        JLabel lblTipo = new JLabel(f.getTipo().name());
        JLabel lblInicio = new JLabel("Início: " + f.getDataInicial());
        JLabel lblFim = new JLabel(
            f.getDataFinal() != null ? "Fim: " + f.getDataFinal() : "Atual"
        );

        lblInstituicao.setBounds(10, 5, 380, 20);
        lblCurso.setBounds(10, 30, 250, 20);
        lblTipo.setBounds(270, 30, 120, 20);
        lblInicio.setBounds(10, 60, 120, 20);
        lblFim.setBounds(150, 60, 120, 20);

        painel.add(lblInstituicao);
        painel.add(lblCurso);
        painel.add(lblTipo);
        painel.add(lblInicio);
        painel.add(lblFim);

        pnlformation.add(painel);
    });

    pnlformation.revalidate();
    pnlformation.repaint();
}

    private void carregarExperiencias() {
    pnlexperience.removeAll(); // limpa tudo antes de redesenhar

    if (perfilcandidato.getExperiencias() == null ||
        perfilcandidato.getExperiencias().isEmpty()) {

        pnlexperience.revalidate();
        pnlexperience.repaint();
        return;
    }

    perfilcandidato.getExperiencias().forEach(exp -> {

        JPanel painel = new JPanel();
        painel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        painel.setBorder(
            javax.swing.BorderFactory.createSoftBevelBorder(
                javax.swing.border.BevelBorder.RAISED
            )
        );

        JLabel lblTitulo = new JLabel(exp.getCargo());
        JLabel lblEmpresa = new JLabel(exp.getEmpresa());
        JLabel lblInicio = new JLabel(
            "Início: " + exp.getDataInicial().toString()
        );

        JLabel lblFim = new JLabel(
            exp.getDataFinal() != null
                ? "Fim: " + exp.getDataFinal().toString()
                : "Atual"
        );

        lblTitulo.setBounds(10, 5, 380, 20);
        lblEmpresa.setBounds(10, 30, 280, 20);
        lblInicio.setBounds(10, 55, 140, 20);
        lblFim.setBounds(160, 55, 140, 20);

        painel.add(lblTitulo);
        painel.add(lblEmpresa);
        painel.add(lblInicio);
        painel.add(lblFim);

        pnlexperience.add(painel);
    });

    pnlexperience.revalidate();
    pnlexperience.repaint();
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadicionarformacao;
    private javax.swing.JButton btncontact;
    private javax.swing.JButton btneditaboutme;
    private javax.swing.JButton btninsert;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jpnpainelcentral;
    private javax.swing.JLabel lblaboutme;
    private javax.swing.JLabel lblcompetence;
    private javax.swing.JLabel lblcompletedname;
    private javax.swing.JLabel lblcoursename;
    private javax.swing.JLabel lbldateend;
    private javax.swing.JLabel lbldateendformation;
    private javax.swing.JLabel lbldatestart;
    private javax.swing.JLabel lbldatestartformation;
    private javax.swing.JLabel lbldescricionaboutme;
    private javax.swing.JLabel lblempresa;
    private javax.swing.JLabel lblexpirence;
    private javax.swing.JLabel lblformation;
    private javax.swing.JLabel lblinstituicion;
    private javax.swing.JLabel lblkingformation;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JPanel pnlexperience;
    private javax.swing.JPanel pnlexpirenceinterne;
    private javax.swing.JPanel pnlformation;
    // End of variables declaration//GEN-END:variables
}
