/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.perfil.candidato.view;

import br.com.ifba.perfil.candidato.controller.PerfilCandidatoIController;
import br.com.ifba.perfil.entity.Experiencia;
import java.time.LocalDate;
import javax.swing.SpinnerNumberModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author USER
 */

@Component
@Scope("prototype")
public class TelaEditarExperiencia extends javax.swing.JFrame {
    
    @Autowired
    private PerfilCandidatoIController perfilcandidatocontroller;
    private Experiencia experiencia;
    private Long idPerfil;
    private TelaApresentacaoCandidato tela;
    
    public void setTelaApresentacaoCandidato(TelaApresentacaoCandidato tela){
        this.tela = tela;
    }
    
    public void setDados(Long idPerfil) {
        this.idPerfil = idPerfil;
    }

    private void configurarSpinners() {
        spnDiaInicial.setModel(new SpinnerNumberModel(1, 1, 31, 1));    // dia início
        spnMesInicial.setModel(new SpinnerNumberModel(1, 1, 12, 1));    // mês início
        spnAnoInicial.setModel(new SpinnerNumberModel(2024, 1900, 2100, 1)); // ano início

        spnDiaFinal.setModel(new SpinnerNumberModel(0, 0, 31, 1));    // dia fim (0 = atual)
        spnMesFinal.setModel(new SpinnerNumberModel(0, 0, 12, 1));    // mês fim
        spnAnoFinal.setModel(new SpinnerNumberModel(0, 0, 2100, 1));  // ano fim
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaEditarExperiencia.class.getName());

    /**
     * Creates new form TelaEditarExperiencia
     */
    public TelaEditarExperiencia() {
        initComponents();
        this.experiencia = new Experiencia();
        configurarSpinners();
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblexperience = new javax.swing.JLabel();
        txttitulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblempresa = new javax.swing.JLabel();
        txtempresa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spnDiaInicial = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        spnMesInicial = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        spnAnoInicial = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        spnDiaFinal = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        spnMesFinal = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        spnAnoFinal = new javax.swing.JSpinner();
        btnsalvarexperiencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblexperience.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblexperience.setText("EXPERIÊNCIAS");

        jLabel1.setText("Título");

        lblempresa.setText("Empresa");

        jLabel2.setText("Data de Início");

        jLabel3.setText("Dia");

        jLabel4.setText("Mês");

        jLabel5.setText("Ano");

        jLabel6.setText("Data de Término");

        jLabel7.setText("Dia");

        jLabel8.setText("Mês");

        jLabel9.setText("Ano");

        btnsalvarexperiencia.setText("SALVAR");
        btnsalvarexperiencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarexperienciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(lblexperience)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnsalvarexperiencia)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(spnDiaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(spnMesFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(spnAnoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel6)
                        .addComponent(jLabel2)
                        .addComponent(lblempresa)
                        .addComponent(jLabel1)
                        .addComponent(txttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtempresa, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(spnDiaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(spnMesInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(spnAnoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblexperience)
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblempresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spnDiaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(spnMesInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(spnAnoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(spnDiaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(spnMesFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(spnAnoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnsalvarexperiencia)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalvarexperienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarexperienciaActionPerformed
        // TODO add your handling code here:

     // ===== VALIDAÇÕES BÁSICAS =====
    if (txttitulo.getText().isBlank()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Informe o título/cargo.");
        return;
    }

    if (txtempresa.getText().isBlank()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Informe a empresa.");
        return;
    }

    int diaIni = (int) spnDiaInicial.getValue();
    int mesIni = (int) spnMesInicial.getValue();
    int anoIni = (int) spnAnoInicial.getValue();

    LocalDate dataInicio;
    try {
        dataInicio = LocalDate.of(anoIni, mesIni, diaIni);
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Data inicial inválida.");
        return;
    }

    // ===== DATA FINAL =====
    int diaFim = (int) spnDiaFinal.getValue();
    int mesFim = (int) spnMesFinal.getValue();
    int anoFim = (int) spnAnoFinal.getValue();

    LocalDate dataFim = null;

    // só cria data se usuário realmente preencheu
    if (anoFim > 0 && mesFim > 0 && diaFim > 0) {
        try {
            dataFim = LocalDate.of(anoFim, mesFim, diaFim);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data final inválida.");
            return;
        }

        // valida lógica temporal
        if (dataFim.isBefore(dataInicio)) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Data final não pode ser anterior à data inicial.");
            return;
        }
    }

    // ===== SET DADOS =====
    experiencia.setCargo(txttitulo.getText());
    experiencia.setEmpresa(txtempresa.getText());
    experiencia.setDataInicial(dataInicio);
    experiencia.setDataFinal(dataFim); // null = atual

    // ===== PERSISTÊNCIA =====
    perfilcandidatocontroller.addExperiencia(idPerfil, experiencia);

    // ===== VOLTA PARA TELA PRINCIPAL =====
    if (tela != null) {
        tela.recarregarPerfil();
        tela.setVisible(true);
    }

    this.dispose();

    }//GEN-LAST:event_btnsalvarexperienciaActionPerformed

 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsalvarexperiencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblempresa;
    private javax.swing.JLabel lblexperience;
    private javax.swing.JSpinner spnAnoFinal;
    private javax.swing.JSpinner spnAnoInicial;
    private javax.swing.JSpinner spnDiaFinal;
    private javax.swing.JSpinner spnDiaInicial;
    private javax.swing.JSpinner spnMesFinal;
    private javax.swing.JSpinner spnMesInicial;
    private javax.swing.JTextField txtempresa;
    private javax.swing.JTextField txttitulo;
    // End of variables declaration//GEN-END:variables
}
