/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.perfil.candidato.view;

import br.com.ifba.perfil.candidato.controller.PerfilCandidatoIController;
import br.com.ifba.perfil.entity.Formacao;
import java.awt.FlowLayout;
import java.util.Set;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author USER
 */

@Component
@Scope("prototype")
public class TelaExcluirFormacao extends javax.swing.JFrame {
    
    @Autowired
    private PerfilCandidatoIController perfilCandidatoController;
    private Long id;
    
    
    public void setDados(Long id) {
        this.id = id;
        carregarFormações();
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaExcluirFormacao.class.getName());

    /**
     * Creates new form TelaExcluirFormacao
     */
    public TelaExcluirFormacao() {
        initComponents();
        
        setSize(500, 600);      // largura x altura
        setLocationRelativeTo(null); // centraliza na tela
        setResizable(false);   // impede redimensionamento
    }
    
    private TelaApresentacaoCandidato telaApresentacao;

    public void setTelaApresentacaoCandidato(TelaApresentacaoCandidato tela) {
        this.telaApresentacao = tela;
    }
    
    private void carregarFormações() {
    pnlListar.removeAll();
    // Define layout vertical para que cada item fique em uma linha
    pnlListar.setLayout(new javax.swing.BoxLayout(pnlListar, javax.swing.BoxLayout.Y_AXIS));

    Set<Formacao> formacoes = perfilCandidatoController.findAllFormacao(id);

    if (formacoes != null) {
        for (Formacao form : formacoes) { 
            pnlListar.add(criarLinha(form)); 
        }
    }
    // FORÇA A ATUALIZAÇÃO VISUAL (Essencial para as informações aparecerem)
    pnlListar.revalidate(); 
    pnlListar.repaint();
    }
    
    private JPanel criarLinha(Formacao form) {
    JPanel linha = new JPanel(new FlowLayout(FlowLayout.LEFT)); 
    linha.setBorder(BorderFactory.createEtchedBorder());

    JLabel lbl = new JLabel("Curso: " + form.getNomeDocurso() + " | Instituição: " + form.getInstituicao()); 
    JButton btnExcluir = new JButton("Excluir"); 
    btnExcluir.setBackground(new java.awt.Color(255, 102, 102)); 
    
    btnExcluir.addActionListener(e -> { 
        int confirma = JOptionPane.showConfirmDialog(this, "Deseja excluir esta formação?");
        if (confirma == JOptionPane.YES_OPTION) {
            // CORREÇÃO: Chamando o método de FORMAÇÃO
            perfilCandidatoController.deletedByIdFormacao(form.getId()); 
            
            // Sincroniza com a tela principal
            if (this.telaApresentacao != null) {
                this.telaApresentacao.recarregarPerfil(); 
            }
            carregarFormações(); // Recarrega a lista local
        }
    });

    linha.add(lbl); 
    linha.add(btnExcluir);
    return linha;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFormacao = new javax.swing.JLabel();
        pnlListar = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFormacao.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblFormacao.setText("FORMAÇÕES");

        javax.swing.GroupLayout pnlListarLayout = new javax.swing.GroupLayout(pnlListar);
        pnlListar.setLayout(pnlListarLayout);
        pnlListarLayout.setHorizontalGroup(
            pnlListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlListarLayout.setVerticalGroup(
            pnlListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addGap(80, 80, 80)
                        .addComponent(lblFormacao)
                        .addGap(0, 151, Short.MAX_VALUE))
                    .addComponent(pnlListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFormacao)
                    .addComponent(btnVoltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        if (this.telaApresentacao != null) {
            // Recarrega o perfil para que as exclusões/edições apareçam na tela principal
            this.telaApresentacao.recarregarPerfil();
            this.telaApresentacao.setVisible(true);
        }
        
        this.dispose(); // Fecha a tela de exclusão/edição
    }//GEN-LAST:event_btnVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblFormacao;
    private javax.swing.JPanel pnlListar;
    // End of variables declaration//GEN-END:variables
}
