/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.perfil.candidato.view;

import br.com.ifba.perfil.candidato.controller.PerfilCandidatoIController;
import br.com.ifba.perfil.entity.Experiencia;
import br.com.ifba.perfil.entity.Formacao;
import br.com.ifba.perfil.enums.TipoFormacao;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author USER
 */

@Component
@Scope("prototype")
public class TelaAdicionarFormacao extends javax.swing.JFrame {
    
    @Autowired
    private PerfilCandidatoIController perfilcandidatocontroller;
    
    private Long idPerfil;
    private Formacao formacaoEmEdicao; // ✅ única fonte da verdade
    private TelaApresentacaoCandidato tela;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaAdicionarFormacao.class.getName());

    
    public TelaAdicionarFormacao() {
        initComponents();
        configurarComponentes();
        setLocationRelativeTo(null);
    }
   
    public void setTelaApresentacaoCandidato(TelaApresentacaoCandidato tela){
        this.tela = tela;
    }

    public void setDados(Long idPerfil) {
        this.idPerfil = idPerfil;
    }
    
    private void configurarComponentes(){
        cmbTipo.addItem(TipoFormacao.CURSO_LIVRE);
        cmbTipo.addItem(TipoFormacao.FUNDAMENTAL);
        cmbTipo.addItem(TipoFormacao.MEDIO);
        cmbTipo.addItem(TipoFormacao.TECNICO);
        cmbTipo.addItem(TipoFormacao.GRADUACAO);
        cmbTipo.addItem(TipoFormacao.POS_GRADUACAO);
        cmbTipo.addItem(TipoFormacao.MESTRADO);
        cmbTipo.addItem(TipoFormacao.DOUTORADO);
        
        spnDiaInicial.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        spnMesInicial.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        spnAnoInicial.setModel(new javax.swing.SpinnerNumberModel(2000, 1900, 2100, 1));


        spnDiaFinal.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        spnMesFinal.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        spnAnoFinal.setModel(new javax.swing.SpinnerNumberModel(2000, 1900, 2100, 1));
    }
    
    //MÉTODO PARA PREENCHER OS CAMPOS NA EDIÇÃO
    public void preencherDados(Formacao form) {
        this.formacaoEmEdicao = form;
        
    txtCurso.setText(form.getNomeDocurso());
    txtIntituicao.setText(form.getInstituicao());
    cmbTipo.setSelectedItem(form.getTipo());

    if (form.getDataInicial() != null) {
        spnDiaInicial.setValue(form.getDataInicial().getDayOfMonth());
        spnMesInicial.setValue(form.getDataInicial().getMonthValue());
        spnAnoInicial.setValue(form.getDataInicial().getYear());
    }

    if (form.getDataFinal() != null) {
        spnDiaFinal.setValue(form.getDataFinal().getDayOfMonth());
        spnMesFinal.setValue(form.getDataFinal().getMonthValue());
        spnAnoFinal.setValue(form.getDataFinal().getYear());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFormacao = new javax.swing.JLabel();
        lblIntituicao = new javax.swing.JLabel();
        txtIntituicao = new javax.swing.JTextField();
        txtCurso = new javax.swing.JTextField();
        lblCurso = new javax.swing.JLabel();
        txtTipo = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        lblDataInicial = new javax.swing.JLabel();
        spnDiaInicial = new javax.swing.JSpinner();
        lblDiaInicial = new javax.swing.JLabel();
        lblMesInicial = new javax.swing.JLabel();
        spnMesInicial = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        spnAnoInicial = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        lblDiaFinal = new javax.swing.JLabel();
        spnDiaFinal = new javax.swing.JSpinner();
        lblMesFinal = new javax.swing.JLabel();
        spnMesFinal = new javax.swing.JSpinner();
        lblAnoFinal = new javax.swing.JLabel();
        spnAnoFinal = new javax.swing.JSpinner();
        btnsalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFormacao.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblFormacao.setText("FORMAÇÃO ACADÊMICA");

        lblIntituicao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIntituicao.setText("INSTITUIÇÃO");

        lblCurso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCurso.setText("CURSO");

        txtTipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTipo.setText("TIPO");

        lblDataInicial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDataInicial.setText("DATA INICIAL");

        lblDiaInicial.setText("DIA");

        lblMesInicial.setText("MÊS");

        jLabel1.setText("ANO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("DATA FINAL");

        lblDiaFinal.setText("DIA");

        lblMesFinal.setText("MÊS");

        lblAnoFinal.setText("ANO");

        btnsalvar.setText("SALVAR");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(lblFormacao))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblIntituicao))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtIntituicao, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblCurso))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(txtTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblDataInicial))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDiaInicial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnDiaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMesInicial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnMesInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnAnoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDiaFinal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnDiaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMesFinal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnMesFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAnoFinal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnAnoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnsalvar)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblFormacao)
                .addGap(4, 4, 4)
                .addComponent(lblIntituicao)
                .addGap(4, 4, 4)
                .addComponent(txtIntituicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lblCurso)
                .addGap(4, 4, 4)
                .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipo))
                .addGap(18, 18, 18)
                .addComponent(lblDataInicial)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiaInicial)
                    .addComponent(spnDiaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMesInicial)
                    .addComponent(spnMesInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(spnAnoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiaFinal)
                    .addComponent(spnDiaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMesFinal)
                    .addComponent(spnMesFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnoFinal)
                    .addComponent(spnAnoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsalvar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        // TODO add your handling code here:
        try {

        // 🔁 DECIDE SE É EDIÇÃO OU NOVO
        Formacao form;

        if (formacaoEmEdicao != null) {
            form = formacaoEmEdicao; // Usa a instância que já veio do banco
        } else {
            form = new Formacao();
        }

        // ===== DATA INICIAL =====
        LocalDate dataInicio = LocalDate.of(
            (int) spnAnoInicial.getValue(),
            (int) spnMesInicial.getValue(),
            (int) spnDiaInicial.getValue()
        );

        // ===== DATA FINAL =====
        LocalDate dataFim = null;
        int diaFim = (int) spnDiaFinal.getValue();
        int mesFim = (int) spnMesFinal.getValue();
        int anoFim = (int) spnAnoFinal.getValue();

        if (diaFim > 0 && mesFim > 0 && anoFim > 0) {
            dataFim = LocalDate.of(anoFim, mesFim, diaFim);
            if (dataFim.isBefore(dataInicio)) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Data final não pode ser anterior à inicial.");
                return;
            }
        }

        // ===== SET DADOS =====
        form.setNomeDocurso(txtCurso.getText());
        form.setInstituicao(txtIntituicao.getText());
        form.setTipo((TipoFormacao) cmbTipo.getSelectedItem());
        form.setDataInicial(dataInicio);
        form.setDataFinal(dataFim);

        // ===== PERSISTÊNCIA =====
        if (formacaoEmEdicao != null) {
            perfilcandidatocontroller.updateFormacao(idPerfil, form);
        } else {
            perfilcandidatocontroller.addFormacao(idPerfil, form);
        }

        // ===== ATUALIZA TELA =====
        if (tela != null) {
            tela.recarregarPerfil();
            tela.setVisible(true);
        }

        dispose();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnsalvarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsalvar;
    private javax.swing.JComboBox<TipoFormacao> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAnoFinal;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblDataInicial;
    private javax.swing.JLabel lblDiaFinal;
    private javax.swing.JLabel lblDiaInicial;
    private javax.swing.JLabel lblFormacao;
    private javax.swing.JLabel lblIntituicao;
    private javax.swing.JLabel lblMesFinal;
    private javax.swing.JLabel lblMesInicial;
    private javax.swing.JSpinner spnAnoFinal;
    private javax.swing.JSpinner spnAnoInicial;
    private javax.swing.JSpinner spnDiaFinal;
    private javax.swing.JSpinner spnDiaInicial;
    private javax.swing.JSpinner spnMesFinal;
    private javax.swing.JSpinner spnMesInicial;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextField txtIntituicao;
    private javax.swing.JLabel txtTipo;
    // End of variables declaration//GEN-END:variables
}
