/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.perfil.candidato.view;

import br.com.ifba.infrastructure.spring.SpringContext;
import br.com.ifba.perfil.candidato.controller.PerfilCandidatoController;
import br.com.ifba.perfil.entity.Experiencia;
import java.awt.FlowLayout;
import java.util.Set;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author USER
 */
@Component
@Scope("prototype")
public class TelaEditarExperiencia extends javax.swing.JFrame {
    
    @Autowired
    private PerfilCandidatoController perfilcandidatocontroller;
    
    private Long id;
    private TelaApresentacaoCandidato telaApresentacao;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaEditarExperiencia.class.getName());

    /**
     * Creates new form TelaEditarExperiencia
     */
    public TelaEditarExperiencia() {
        initComponents();
        this.setLocationRelativeTo(null);
        // Define layout vertical para o painel de listagem
        pnlListar.setLayout(new javax.swing.BoxLayout(pnlListar, javax.swing.BoxLayout.Y_AXIS));
    }
    
    public void setDados(Long id){
        this.id = id;
        carregarExperiencias();
    }
    
    private void carregarExperiencias(){
        pnlListar.removeAll();
        
        Set<Experiencia> experiencias = perfilcandidatocontroller.findAllExperiencia(id);
        
        if(experiencias != null){
            for (Experiencia exp : experiencias){
                pnlListar.add(criarLinha(exp));
            }
        }
        
        pnlListar.revalidate();
        pnlListar.repaint();
    }
    
    private JPanel criarLinha(Experiencia exp) {
        JPanel linha = new JPanel(new FlowLayout(FlowLayout.LEFT));
        linha.setBorder(BorderFactory.createEtchedBorder());

        JLabel lbl = new JLabel(exp.getCargo() + " na " + exp.getEmpresa());
        JButton btnEditar = new JButton("Editar");
        
        // Ação do Botão Editar
        btnEditar.addActionListener(e -> {
            // Pega a tela de formulário (a mesma que você usa para inserir)
            TelaAdicionarExperiencia telaForm = SpringContext.getBean(TelaAdicionarExperiencia.class);
            
            // Você precisará criar este método 'preencherDados' na sua tela de formulário
            telaForm.setDados(id); 
            telaForm.preencherDados(exp.getId()); 
            telaForm.setTelaApresentacaoCandidato(this.telaApresentacao);
            
            telaForm.setVisible(true);
            this.dispose(); // Fecha a lista de seleção
        });

        linha.add(lbl);
        linha.add(btnEditar);
        return linha;
    }
    
    public void setTelaApresentacaoCandidato(TelaApresentacaoCandidato tela) {
        this.telaApresentacao = tela;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblExperiencias = new javax.swing.JLabel();
        pnlListar = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblExperiencias.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblExperiencias.setText("EXPERIÊNCIAS");

        javax.swing.GroupLayout pnlListarLayout = new javax.swing.GroupLayout(pnlListar);
        pnlListar.setLayout(pnlListarLayout);
        pnlListarLayout.setHorizontalGroup(
            pnlListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        pnlListarLayout.setVerticalGroup(
            pnlListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnVoltar)
                        .addGap(51, 51, 51)
                        .addComponent(lblExperiencias))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExperiencias)
                    .addComponent(btnVoltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        if (this.telaApresentacao != null) {
            this.telaApresentacao.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblExperiencias;
    private javax.swing.JPanel pnlListar;
    // End of variables declaration//GEN-END:variables
}
