/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.perfil.candidato.view;

import br.com.ifba.perfil.candidato.controller.PerfilCandidatoIController;
import br.com.ifba.perfil.entity.Experiencia;
import java.awt.FlowLayout;
import java.util.Set;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author USER
 */

@Component
@Scope("prototype")
public class TelaExcluirExperiencia extends javax.swing.JFrame {
    
    @Autowired
    private PerfilCandidatoIController perfilCandidatoController;
    private Long id;
    
    public void setDados(Long id) {
        this.id = id;
        carregarExperiencias();
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaExcluirExperiencia.class.getName());

    /**
     * Creates new form TelaExcluirExperiencia
     */
    public TelaExcluirExperiencia() {
        initComponents();
        
        setSize(500, 600);      // largura x altura
        setLocationRelativeTo(null); // centraliza na tela
        setResizable(false);   // impede redimensionamento
    }
    
    private TelaApresentacaoCandidato telaApresentacao;

    public void setTelaApresentacaoCandidato(TelaApresentacaoCandidato tela) {
        this.telaApresentacao = tela;
    }
    
    private void carregarExperiencias() {
    pnlListar.removeAll();
    // Define layout vertical para que cada item fique em uma linha
    pnlListar.setLayout(new javax.swing.BoxLayout(pnlListar, javax.swing.BoxLayout.Y_AXIS));

    Set<Experiencia> experiencias = perfilCandidatoController.findAllExperiencia(id);

    if (experiencias != null) {
        for (Experiencia exp : experiencias) { 
            pnlListar.add(criarLinha(exp)); 
        }
    }

    // FORÇA A ATUALIZAÇÃO VISUAL (Essencial para as informações aparecerem)
    pnlListar.revalidate(); 
    pnlListar.repaint(); 
}
    
    private JPanel criarLinha(Experiencia exp) {
    JPanel linha = new JPanel(new FlowLayout(FlowLayout.LEFT)); 
    linha.setBorder(BorderFactory.createEtchedBorder());

    JLabel lbl = new JLabel("Cargo: " + exp.getCargo() + " | Empresa: " + exp.getEmpresa()); 
    JButton btnExcluir = new JButton("Excluir"); 
    btnExcluir.setBackground(new java.awt.Color(255, 102, 102)); 
    
    btnExcluir.addActionListener(e -> { 
        int confirma = JOptionPane.showConfirmDialog(this, "Deseja excluir esta experiência?");
        if (confirma == JOptionPane.YES_OPTION) {
            // Chama o controller para deletar
            perfilCandidatoController.deletedByIdExperiencia(exp.getId()); 
            
            // ATUALIZAÇÃO IMEDIATA: Força a tela de baixo a buscar do banco
            if (this.telaApresentacao != null) {
                this.telaApresentacao.recarregarPerfil(); 
            }
            carregarExperiencias(); // Recarrega a lista desta janela
        }
    });

    linha.add(lbl); 
    linha.add(btnExcluir);
    return linha;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlListar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout pnlListarLayout = new javax.swing.GroupLayout(pnlListar);
        pnlListar.setLayout(pnlListarLayout);
        pnlListarLayout.setHorizontalGroup(
            pnlListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlListarLayout.setVerticalGroup(
            pnlListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("EXPERIÊNCIAS");

        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1)
                        .addGap(0, 152, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnVoltar))
                .addGap(4, 4, 4)
                .addComponent(pnlListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        if (this.telaApresentacao != null) {
            // Recarrega o perfil para que as exclusões/edições apareçam na tela principal
            this.telaApresentacao.recarregarPerfil();
            this.telaApresentacao.setVisible(true);
        }
        
        this.dispose(); // Fecha a tela de exclusão/edição
    }//GEN-LAST:event_btnVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlListar;
    // End of variables declaration//GEN-END:variables
}
