/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.perfil.candidato.view;

import br.com.ifba.infrastructure.spring.SpringContext;
import br.com.ifba.perfil.candidato.controller.PerfilCandidatoIController;
import br.com.ifba.perfil.entity.Experiencia;
import br.com.ifba.perfil.entity.Formacao;
import br.com.ifba.perfil.entity.PerfilCandidato;
import java.util.Collections;
import java.util.Set;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author USER
 */

@Component
@Scope("prototype")
public class TelaApresentacao extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaApresentacao.class.getName());

    @Autowired
    private PerfilCandidatoIController perfilcandidatocontroller;
    
    private PerfilCandidato perfilcandidato;
    
    // COMPONENTES PRINCIPAIS
    private JPanel pnlExperiencias;
    private JPanel pnlFormacoes;
    
    public void setPerfilCandidato(PerfilCandidato perfil) {
        this.perfilcandidato = perfil;
        atualizarTela(); //carrega as experiencias de forma dinamica
    }
    
    private void atualizarTela() {
        if (perfilcandidato == null) return;

        lblcompletedname.setText(perfilcandidato.getUsuarioPerfil().getNome());
        lbldescricionaboutme.setText(perfilcandidato.getSobre());

        carregarExperiencias();
        carregarFormacoes();
    }
    
    // ======================
    // Métodod Usado para carregar as experiências inseridas, para que a tela principal se mantenha atualizada    
    // ======================
    private void carregarExperiencias() {
        pnlExperiencias.removeAll();

        Set<Experiencia> experiencias =
        perfilcandidato.getExperiencias() != null ? perfilcandidato.getExperiencias() : Collections.EMPTY_SET;

        experiencias.forEach(exp -> pnlExperiencias.add(criarPainelExperiencia(exp)));

        pnlExperiencias.revalidate();
        pnlExperiencias.repaint();
    }
    
    //Método usado para criar um novo painel toda vez que uma experiencia for adicionada
    private JPanel criarPainelExperiencia(Experiencia exp) {
        JPanel painel = new JPanel();
        painel.setLayout(new BoxLayout(painel, BoxLayout.Y_AXIS));
        painel.setBorder(BorderFactory.createEtchedBorder());

        painel.add(new JLabel(exp.getCargo()));
        painel.add(new JLabel(exp.getEmpresa()));
        painel.add(new JLabel("Início: " + exp.getDataInicial()));
        painel.add(new JLabel(
        exp.getDataFinal() != null ? "Fim: " + exp.getDataFinal() : "Atual"
        ));
        
        return painel;
    }
    
    // ======================
    // Métodod Usado para carregar as formações inseridas, para que a tela principal se mantenha atualizada    
    // ======================
    private void carregarFormacoes() {
        pnlFormacoes.removeAll();

        Set<Formacao> formacoes =
        perfilcandidato.getFormacaoAcademica() != null ? perfilcandidato.getFormacaoAcademica() : Collections.EMPTY_SET;

        formacoes.forEach(f -> pnlFormacoes.add(criarPainelFormacao(f)));

        pnlFormacoes.revalidate();
        pnlFormacoes.repaint();
    }
    
    //Método usado para criar um novo painel toda vez que uma formação for adicionada
    private JPanel criarPainelFormacao(Formacao f) {
        JPanel painel = new JPanel();
        painel.setLayout(new BoxLayout(painel, BoxLayout.Y_AXIS));
        painel.setBorder(BorderFactory.createEtchedBorder());


        painel.add(new JLabel(f.getInstituicao()));
        painel.add(new JLabel(f.getTipo().name() + " - " + f.getNomeDocurso()));
        painel.add(new JLabel("Início: " + f.getDataInicial()));
        painel.add(new JLabel(
        f.getDataFinal() != null ? "Fim: " + f.getDataFinal() : "Atual"
        ));

        return painel;
    }
    
    // ======================
        // RECARREGAR PERFIL
    // ======================
    public void recarregarPerfil() {
        PerfilCandidato atualizado = perfilcandidatocontroller
            .findByUsuarioPerfilNome(perfilcandidato.getUsuarioPerfil().getNome());
        setPerfilCandidato(atualizado);
        setVisible(true);
    }
    
    public TelaApresentacao() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnpainelcentral = new javax.swing.JPanel();
        lblcompletedname = new javax.swing.JLabel();
        lblaboutme = new javax.swing.JLabel();
        lbldescricionaboutme = new javax.swing.JLabel();
        btncontact = new javax.swing.JButton();
        pnlexperience = new javax.swing.JPanel();
        pnlexpirenceinterne = new javax.swing.JPanel();
        lbltitulo = new javax.swing.JLabel();
        lblempresa = new javax.swing.JLabel();
        lbldatestart = new javax.swing.JLabel();
        lbldateend = new javax.swing.JLabel();
        lblexpirence = new javax.swing.JLabel();
        btneditaboutme = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btninsert = new javax.swing.JButton();
        lblformation = new javax.swing.JLabel();
        pnlformation = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblinstituicion = new javax.swing.JLabel();
        lblkingformation = new javax.swing.JLabel();
        lblcoursename = new javax.swing.JLabel();
        lbldatestartformation = new javax.swing.JLabel();
        lbldateendformation = new javax.swing.JLabel();
        lblcompetence = new javax.swing.JLabel();
        pnlcompetencia = new javax.swing.JPanel();
        lblNomeCompetencia = new javax.swing.JLabel();
        btnadicionarformacao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btninserircompetencia = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblIdioma = new javax.swing.JLabel();
        pnlIdioma = new javax.swing.JPanel();
        lblNomeIdioma = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        btninseriridioma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jpnpainelcentral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcompletedname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpnpainelcentral.add(lblcompletedname, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 6, 410, 40));

        lblaboutme.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblaboutme.setText("SOBRE MIM");
        jpnpainelcentral.add(lblaboutme, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 70, 10));

        lbldescricionaboutme.setBackground(new java.awt.Color(255, 255, 255));
        lbldescricionaboutme.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbldescricionaboutme.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                lbldescricionaboutmeComponentAdded(evt);
            }
        });
        jpnpainelcentral.add(lbldescricionaboutme, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 420, 70));

        btncontact.setBackground(new java.awt.Color(204, 0, 153));
        btncontact.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btncontact.setForeground(new java.awt.Color(255, 255, 255));
        btncontact.setText("INFORMAÇÕES DE CONTATO");
        jpnpainelcentral.add(btncontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        pnlexperience.setBackground(new java.awt.Color(255, 255, 255));
        pnlexperience.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlexperience.setLayout(new javax.swing.BoxLayout(pnlexperience, javax.swing.BoxLayout.LINE_AXIS));

        pnlexpirenceinterne.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlexpirenceinterne.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltitulo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlexpirenceinterne.add(lbltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 5, 380, 20));

        lblempresa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlexpirenceinterne.add(lblempresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 280, 20));

        lbldatestart.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlexpirenceinterne.add(lbldatestart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 140, 20));

        lbldateend.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlexpirenceinterne.add(lbldateend, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 130, 20));

        pnlexperience.add(pnlexpirenceinterne);

        jpnpainelcentral.add(pnlexperience, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 420, 110));

        lblexpirence.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblexpirence.setText("EXPERIÊNCIAS");
        jpnpainelcentral.add(lblexpirence, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        btneditaboutme.setBackground(new java.awt.Color(242, 242, 242));
        btneditaboutme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/editar.png"))); // NOI18N
        btneditaboutme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditaboutmeActionPerformed(evt);
            }
        });
        jpnpainelcentral.add(btneditaboutme, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 30, 20));

        jButton1.setBackground(new java.awt.Color(242, 242, 242));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/editar.png"))); // NOI18N
        jpnpainelcentral.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 30, 20));

        btninsert.setBackground(new java.awt.Color(242, 242, 242));
        btninsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cadastrar.png"))); // NOI18N
        btninsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertActionPerformed(evt);
            }
        });
        jpnpainelcentral.add(btninsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 30, 20));

        lblformation.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblformation.setText("FORMAÇÕES ");
        jpnpainelcentral.add(lblformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        pnlformation.setBackground(new java.awt.Color(255, 255, 255));
        pnlformation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlformation.setLayout(new javax.swing.BoxLayout(pnlformation, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblinstituicion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lblinstituicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 20));

        lblkingformation.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lblkingformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, 20));

        lblcoursename.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lblcoursename, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 250, 20));

        lbldatestartformation.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lbldatestartformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 120, 20));

        lbldateendformation.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lbldateendformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 120, 20));

        pnlformation.add(jPanel1);

        jpnpainelcentral.add(pnlformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 420, 110));

        lblcompetence.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblcompetence.setText("COMPETÊNCIAS");
        jpnpainelcentral.add(lblcompetence, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, -1, -1));

        pnlcompetencia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlcompetencia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNomeCompetencia.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlcompetencia.add(lblNomeCompetencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 20));

        jpnpainelcentral.add(pnlcompetencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 420, 110));

        btnadicionarformacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cadastrar.png"))); // NOI18N
        btnadicionarformacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadicionarformacaoActionPerformed(evt);
            }
        });
        jpnpainelcentral.add(btnadicionarformacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 337, -1, 20));

        jLabel1.setText("jLabel1");
        jpnpainelcentral.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btninserircompetencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cadastrar.png"))); // NOI18N
        jpnpainelcentral.add(btninserircompetencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 30, 20));

        jLabel3.setText("jLabel3");
        jpnpainelcentral.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblIdioma.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblIdioma.setText("IDIOMA");
        jpnpainelcentral.add(lblIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, -1, -1));

        pnlIdioma.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlIdioma.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNomeIdioma.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlIdioma.add(lblNomeIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 20));

        lblNivel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlIdioma.add(lblNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 190, 20));

        jpnpainelcentral.add(pnlIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 420, 90));

        btninseriridioma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cadastrar.png"))); // NOI18N
        jpnpainelcentral.add(btninseriridioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 620, -1, 20));

        getContentPane().add(jpnpainelcentral);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbldescricionaboutmeComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_lbldescricionaboutmeComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lbldescricionaboutmeComponentAdded

    private void btneditaboutmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditaboutmeActionPerformed
        TelaEditarSobreMim tela = SpringContext.getBean(TelaEditarSobreMim.class);
        tela.setDados(perfilcandidato.getId(), perfilcandidato.getSobre());
        tela.setTelaApresentacao(this);
        tela.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btneditaboutmeActionPerformed

    private void btninsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertActionPerformed
        TelaEditarExperiencia tela = SpringContext.getBean(TelaEditarExperiencia.class);
        tela.setDados(perfilcandidato.getId());
        tela.setTelaApresentacao(this);
        tela.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btninsertActionPerformed

    private void btnadicionarformacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadicionarformacaoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnadicionarformacaoActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadicionarformacao;
    private javax.swing.JButton btncontact;
    private javax.swing.JButton btneditaboutme;
    private javax.swing.JButton btninserircompetencia;
    private javax.swing.JButton btninseriridioma;
    private javax.swing.JButton btninsert;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpnpainelcentral;
    private javax.swing.JLabel lblIdioma;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNomeCompetencia;
    private javax.swing.JLabel lblNomeIdioma;
    private javax.swing.JLabel lblaboutme;
    private javax.swing.JLabel lblcompetence;
    private javax.swing.JLabel lblcompletedname;
    private javax.swing.JLabel lblcoursename;
    private javax.swing.JLabel lbldateend;
    private javax.swing.JLabel lbldateendformation;
    private javax.swing.JLabel lbldatestart;
    private javax.swing.JLabel lbldatestartformation;
    private javax.swing.JLabel lbldescricionaboutme;
    private javax.swing.JLabel lblempresa;
    private javax.swing.JLabel lblexpirence;
    private javax.swing.JLabel lblformation;
    private javax.swing.JLabel lblinstituicion;
    private javax.swing.JLabel lblkingformation;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JPanel pnlIdioma;
    private javax.swing.JPanel pnlcompetencia;
    private javax.swing.JPanel pnlexperience;
    private javax.swing.JPanel pnlexpirenceinterne;
    private javax.swing.JPanel pnlformation;
    // End of variables declaration//GEN-END:variables
}
