/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.perfil.candidato.view;

import br.com.ifba.perfil.candidato.controller.PerfilCandidatoIController;
import br.com.ifba.perfil.entity.Competencia;
import br.com.ifba.perfil.entity.Idioma;
import br.com.ifba.perfil.enums.Nivel;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author USER
 */
@Component
@Scope("prototype")
public class TelaAdicionarIdioma extends javax.swing.JFrame {
    
    @Autowired
    private PerfilCandidatoIController perfilcandidatocontroller;
    
    private Long idPerfil;
    private Idioma idiomaEmEdicao;
    private TelaApresentacaoCandidato tela;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaAdicionarIdioma.class.getName());

    /**
     * Creates new form TelaEditarIdioma
     */
    public TelaAdicionarIdioma() {
        initComponents();
        carregarNiveis();
        this.setLocationRelativeTo(null);       
    }
    
    
    public void setTelaApresentacaoCandidato(TelaApresentacaoCandidato tela) {
        this.tela = tela;
    }
    
    
    public void setDados(Long idPerfil) {
        this.idPerfil = idPerfil;
    }
    
    private void carregarNiveis(){
        cmbNivel.addItem(Nivel.AVANCADO);
        cmbNivel.addItem(Nivel.BASICO);
        cmbNivel.addItem(Nivel.INTERMEDIARIO);
        
    }
    
    //MÉTODO PARA PREENCHER OS CAMPOS NA EDIÇÃO
    public void preencherDados(Idioma idioma) {
        this.idiomaEmEdicao = idioma;
        
    txtNomeIdioma.setText(idioma.getIdioma());
    cmbNivel.setSelectedItem(idioma.getNivel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIdioma = new javax.swing.JLabel();
        lblNomeIdioma = new javax.swing.JLabel();
        txtNomeIdioma = new javax.swing.JTextField();
        lblNivel = new javax.swing.JLabel();
        cmbNivel = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblIdioma.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblIdioma.setText("IDIOMA");

        lblNomeIdioma.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNomeIdioma.setText("Nome");

        txtNomeIdioma.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNivel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNivel.setText("Nível");

        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(lblIdioma))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeIdioma)
                            .addComponent(txtNomeIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNivel)
                            .addComponent(cmbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(btnSalvar)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblIdioma)
                .addGap(41, 41, 41)
                .addComponent(lblNomeIdioma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNivel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        String nome = txtNomeIdioma.getText().trim();
        Nivel nivel = (Nivel) cmbNivel.getSelectedItem();
        
        try {
        Idioma idioma;
        
        // Se houver uma competência em edição, usamos ela (mesma representação)
        if (this.idiomaEmEdicao != null) {
            idioma = this.idiomaEmEdicao;
        } else {
            idioma = new Idioma();
        }

        idioma.setIdioma(nome);
        idioma.setNivel(nivel);
        
        if (this.idiomaEmEdicao != null) {
            // Chama o update para sincronizar a instância existente
            perfilcandidatocontroller.updateIdioma(idPerfil, idioma);
        } else {
            // Chama o add para nova competência
            perfilcandidatocontroller.addIdioma(idPerfil, idioma);
        }

        JOptionPane.showMessageDialog(this, "Salvo com sucesso!");
        
        if (this.tela != null) {
            this.tela.recarregarPerfil(); 
        }
        this.dispose();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<Nivel> cmbNivel;
    private javax.swing.JLabel lblIdioma;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNomeIdioma;
    private javax.swing.JTextField txtNomeIdioma;
    // End of variables declaration//GEN-END:variables
}
